import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import initSqlJs from 'sql.js'
import { drizzle } from 'drizzle-orm/sql-js'
import { migrateSqlite } from '../src/migrate-sqlite.js'

type Journal = { entries: { idx: number; tag: string; when: number; breakpoints: boolean }[] }

/**
 * Renders drizzle/sqlite as a browser-safe TS module of drizzle `MigrationMeta` (+ tag), in journal order — the same
 * shape drizzle's `readMigrationFiles` returns, but with line endings normalised to \n before splitting and hashing,
 * so the output is identical on Windows (CRLF checkout) and CI (LF). drizzle decides by `created_at` only, never by
 * `hash`. Also records the tables and triggers `migrateSqlite` leaves in a fresh database (spike S2 and tests).
 */
export async function renderMigrationsModule(folder: string): Promise<string> {
  const journal = JSON.parse(readFileSync(join(folder, 'meta', '_journal.json'), 'utf8')) as Journal
  const migrations = [...journal.entries]
    .sort((a, b) => a.idx - b.idx)
    .map((e) => {
      const text = readFileSync(join(folder, `${e.tag}.sql`), 'utf8').replace(/\r\n/g, '\n')
      return { tag: e.tag, sql: text.split('--> statement-breakpoint'), bps: e.breakpoints, folderMillis: e.when, hash: createHash('sha256').update(text).digest('hex') }
    })

  const SQL = await initSqlJs()
  const raw = new SQL.Database()
  let tables: string[] = []
  let triggers: string[] = []
  try {
    migrateSqlite(drizzle(raw), folder)
    const names = (type: string): string[] =>
      (raw.exec(`select name from sqlite_master where type = '${type}' and name not like 'sqlite_%' and name not like '__drizzle%' order by name`)[0]?.values ?? []).map((r) => String(r[0]))
    tables = names('table')
    triggers = names('trigger')
  } finally {
    raw.close()
  }

  return [
    '// GENERATED by scripts/gen-sqlite-migrations.cli.ts from drizzle/sqlite — do not edit by hand.',
    '// Regenerate: pnpm --filter @dayo/db-schema gen:browser',
    "import type { BundledMigration } from './types.js'",
    '',
    `export const SQLITE_MIGRATIONS: readonly BundledMigration[] = ${JSON.stringify(migrations, null, 2)}`,
    '',
    '/** Tables and triggers that migrateSqlite leaves in a fresh database. */',
    `export const SQLITE_TABLES: readonly string[] = ${JSON.stringify(tables)}`,
    `export const SQLITE_TRIGGERS: readonly string[] = ${JSON.stringify(triggers)}`,
    '',
  ].join('\n')
}
