// GENERATED by scripts/gen-sqlite-migrations.cli.ts from drizzle/sqlite — do not edit by hand.
// Regenerate: pnpm --filter @dayo/db-schema gen:browser
import type { BundledMigration } from './types.js'

export const SQLITE_MIGRATIONS: readonly BundledMigration[] = [
  {
    "tag": "0000_baseline",
    "sql": [
      "CREATE TABLE `bom` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`item_id` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\t`yield_milli` integer NOT NULL,\n\t`is_current` integer NOT NULL,\n\t`instructions` text,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `bom_current_uq` ON `bom` (`item_id`) WHERE is_current;",
      "\nCREATE TABLE `bom_line` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`bom_id` text NOT NULL,\n\t`component_item_id` text NOT NULL,\n\t`qty_milli` integer NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\tFOREIGN KEY (`bom_id`) REFERENCES `bom`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`component_item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `category` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`name` text NOT NULL,\n\t`sort` integer NOT NULL,\n\t`is_active` integer NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `category_code_unique` ON `category` (`code`);",
      "\nCREATE TABLE `channel` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`name` text NOT NULL,\n\t`commission_bp` integer NOT NULL,\n\t`is_active` integer NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `channel_code_unique` ON `channel` (`code`);",
      "\nCREATE TABLE `customer` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`line_user_id` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`picture_url` text,\n\t`first_seen_at` text NOT NULL,\n\t`last_order_at` text,\n\t`is_blocked` integer NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `customer_line_user_id_unique` ON `customer` (`line_user_id`);",
      "\nCREATE TABLE `device` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`receipt_prefix` text NOT NULL,\n\t`is_selling_device` integer NOT NULL,\n\t`registered_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `device_receipt_prefix_unique` ON `device` (`receipt_prefix`);",
      "\nCREATE TABLE `equipment` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`name` text NOT NULL,\n\t`purchased_at` text,\n\t`price_satang` integer NOT NULL,\n\t`qty` integer NOT NULL,\n\t`supplier` text,\n\t`life_months` integer,\n\t`condition` text,\n\t`owner` text,\n\t`note` text,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `equipment_code_unique` ON `equipment` (`code`);",
      "\nCREATE TABLE `item` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`name` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`category` text NOT NULL,\n\t`use_unit` text NOT NULL,\n\t`is_tracked` integer NOT NULL,\n\t`reorder_point_milli` integer NOT NULL,\n\t`standard_cost_usat` integer NOT NULL,\n\t`shelf_life_hours` integer,\n\t`is_active` integer NOT NULL,\n\t`note` text,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `item_code_unique` ON `item` (`code`);",
      "\nCREATE TABLE `price` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`variant_id` text NOT NULL,\n\t`channel_id` text NOT NULL,\n\t`price_satang` integer NOT NULL,\n\t`effective_from` text NOT NULL,\n\t`created_by` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\tFOREIGN KEY (`variant_id`) REFERENCES `product_variant`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`channel_id`) REFERENCES `channel`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `price_variant_id_channel_id_effective_from_unique` ON `price` (`variant_id`,`channel_id`,`effective_from`);",
      "\nCREATE TABLE `product` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`name_th` text NOT NULL,\n\t`name_en` text NOT NULL,\n\t`category_id` text NOT NULL,\n\t`sort` integer NOT NULL,\n\t`is_active` integer NOT NULL,\n\t`prep_group` text,\n\t`sold_out_until` text,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\tFOREIGN KEY (`category_id`) REFERENCES `category`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `product_code_unique` ON `product` (`code`);",
      "\nCREATE TABLE `product_variant` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`product_id` text NOT NULL,\n\t`size_id` text NOT NULL,\n\t`sku` text NOT NULL,\n\t`is_active` integer NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\tFOREIGN KEY (`product_id`) REFERENCES `product`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`size_id`) REFERENCES `size`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `product_variant_sku_unique` ON `product_variant` (`sku`);",
      "\nCREATE UNIQUE INDEX `product_variant_product_id_size_id_unique` ON `product_variant` (`product_id`,`size_id`);",
      "\nCREATE TABLE `purchase_unit` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`item_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`qty_per_unit_milli` integer NOT NULL,\n\t`is_default` integer NOT NULL,\n\t`barcode` text,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\tFOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `recipe` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`variant_id` text NOT NULL,\n\t`sweetness_id` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\t`effective_from` text NOT NULL,\n\t`is_current` integer NOT NULL,\n\t`created_by` text,\n\t`note` text,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`variant_id`) REFERENCES `product_variant`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`sweetness_id`) REFERENCES `sweetness_level`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `recipe_current_uq` ON `recipe` (`variant_id`,`sweetness_id`) WHERE is_current;",
      "\nCREATE UNIQUE INDEX `recipe_variant_id_sweetness_id_version_unique` ON `recipe` (`variant_id`,`sweetness_id`,`version`);",
      "\nCREATE TABLE `recipe_line` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`recipe_id` text NOT NULL,\n\t`item_id` text NOT NULL,\n\t`qty_milli` integer NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\tFOREIGN KEY (`recipe_id`) REFERENCES `recipe`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `setting` (\n\t`key` text NOT NULL,\n\t`value_json` text NOT NULL,\n\t`effective_from` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\tPRIMARY KEY(`key`, `effective_from`)\n);\n",
      "\nCREATE TABLE `size` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`name` text NOT NULL,\n\t`sort` integer NOT NULL,\n\t`packaging_item_id` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL,\n\tFOREIGN KEY (`packaging_item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `size_code_unique` ON `size` (`code`);",
      "\nCREATE TABLE `sweetness_level` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`code` text NOT NULL,\n\t`name` text NOT NULL,\n\t`sort` integer NOT NULL,\n\t`is_default` integer NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL\n);\n",
      "\nCREATE UNIQUE INDEX `sweetness_level_code_unique` ON `sweetness_level` (`code`);",
      "\nCREATE TABLE `user` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`display_name` text NOT NULL,\n\t`role` text NOT NULL,\n\t`pin_hash` text NOT NULL,\n\t`is_active` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`version` integer DEFAULT 1 NOT NULL\n);\n",
      "\nCREATE TABLE `item_cost_state` (\n\t`item_id` text PRIMARY KEY NOT NULL,\n\t`on_hand_milli` integer NOT NULL,\n\t`avg_cost_usat` integer NOT NULL,\n\t`as_of_movement_id` text,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `production_batch` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`bom_id` text NOT NULL,\n\t`item_id` text NOT NULL,\n\t`business_date` text NOT NULL,\n\t`scale_bp` integer NOT NULL,\n\t`yield_actual_milli` integer NOT NULL,\n\t`unit_cost_usat` integer NOT NULL,\n\t`batch_cost_satang` integer NOT NULL,\n\t`expires_at` text,\n\t`device_id` text,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`bom_id`) REFERENCES `bom`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `purchase` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`business_date` text NOT NULL,\n\t`supplier` text,\n\t`total_satang` integer NOT NULL,\n\t`receipt_image_ref` text,\n\t`note` text,\n\t`device_id` text,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `purchase_line` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`purchase_id` text NOT NULL,\n\t`item_id` text NOT NULL,\n\t`purchase_unit_id` text,\n\t`qty_units_milli` integer NOT NULL,\n\t`qty_use_milli` integer NOT NULL,\n\t`line_total_satang` integer NOT NULL,\n\tFOREIGN KEY (`purchase_id`) REFERENCES `purchase`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`purchase_unit_id`) REFERENCES `purchase_unit`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `purchase_line_purchase_idx` ON `purchase_line` (`purchase_id`);",
      "\nCREATE TABLE `stock_count` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`business_date` text NOT NULL,\n\t`status` text NOT NULL,\n\t`device_id` text,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`closed_by` text,\n\t`closed_at` text,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`closed_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `stock_count_line` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`count_id` text NOT NULL,\n\t`item_id` text NOT NULL,\n\t`purchase_unit_id` text,\n\t`counted_units_milli` integer NOT NULL,\n\t`counted_use_milli` integer NOT NULL,\n\t`expected_use_milli` integer NOT NULL,\n\t`variance_use_milli` integer NOT NULL,\n\t`variance_satang` integer NOT NULL,\n\tFOREIGN KEY (`count_id`) REFERENCES `stock_count`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`purchase_unit_id`) REFERENCES `purchase_unit`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `stock_count_line_count_id_item_id_unique` ON `stock_count_line` (`count_id`,`item_id`);",
      "\nCREATE TABLE `stock_movement` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`item_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`qty_milli` integer NOT NULL,\n\t`unit_cost_usat` integer NOT NULL,\n\t`ref_type` text NOT NULL,\n\t`ref_id` text NOT NULL,\n\t`business_date` text NOT NULL,\n\t`device_id` text,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`item_id`) REFERENCES `item`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT \"stock_movement_qty_nonzero_ck\" CHECK(\"stock_movement\".\"qty_milli\" <> 0)\n);\n",
      "\nCREATE INDEX `stock_movement_item_created_idx` ON `stock_movement` (`item_id`,`created_at`);",
      "\nCREATE INDEX `stock_movement_ref_idx` ON `stock_movement` (`ref_type`,`ref_id`);",
      "\nCREATE INDEX `stock_movement_item_date_idx` ON `stock_movement` (`item_id`,`business_date`);",
      "\nCREATE INDEX `stock_movement_business_date_idx` ON `stock_movement` (`business_date`);",
      "\nCREATE TABLE `cash_count` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`shift_id` text NOT NULL,\n\t`counted_satang` integer NOT NULL,\n\t`expected_satang` integer NOT NULL,\n\t`variance_satang` integer NOT NULL,\n\t`reason` text,\n\t`lines_json` text NOT NULL,\n\t`counted_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`shift_id`) REFERENCES `shift`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`counted_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `cash_count_shift_idx` ON `cash_count` (`shift_id`);",
      "\nCREATE TABLE `cash_movement` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`shift_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`amount_satang` integer NOT NULL,\n\t`order_id` text,\n\t`reason` text,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`shift_id`) REFERENCES `shift`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT \"cash_movement_void_refund_order_ck\" CHECK((\"cash_movement\".\"kind\" = 'VOID_REFUND') = (\"cash_movement\".\"order_id\" is not null)),\n\tCONSTRAINT \"cash_movement_amount_positive_ck\" CHECK(\"cash_movement\".\"amount_satang\" > 0)\n);\n",
      "\nCREATE INDEX `cash_movement_shift_idx` ON `cash_movement` (`shift_id`);",
      "\nCREATE INDEX `cash_movement_order_idx` ON `cash_movement` (`order_id`);",
      "\nCREATE TABLE `discount` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`amount_satang` integer NOT NULL,\n\t`reason` text NOT NULL,\n\t`approved_by` text NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`approved_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `discount_order_idx` ON `discount` (`order_id`);",
      "\nCREATE TABLE `order` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`origin` text NOT NULL,\n\t`device_id` text,\n\t`receipt_no` text,\n\t`queue_no` integer,\n\t`business_date` text NOT NULL,\n\t`shift_id` text,\n\t`channel_id` text NOT NULL,\n\t`customer_id` text,\n\t`status` text NOT NULL,\n\t`subtotal_satang` integer NOT NULL,\n\t`discount_satang` integer NOT NULL,\n\t`total_satang` integer NOT NULL,\n\t`vat_satang` integer NOT NULL,\n\t`cost_satang` integer NOT NULL,\n\t`note` text,\n\t`created_by_type` text NOT NULL,\n\t`created_by_id` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`paid_at` text,\n\t`ready_at` text,\n\t`voided_at` text,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`shift_id`) REFERENCES `shift`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`channel_id`) REFERENCES `channel`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`customer_id`) REFERENCES `customer`(`id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT \"order_subtotal_nonneg_ck\" CHECK(\"order\".\"subtotal_satang\" >= 0),\n\tCONSTRAINT \"order_discount_nonneg_ck\" CHECK(\"order\".\"discount_satang\" >= 0),\n\tCONSTRAINT \"order_total_nonneg_ck\" CHECK(\"order\".\"total_satang\" >= 0),\n\tCONSTRAINT \"order_discount_le_subtotal_ck\" CHECK(\"order\".\"discount_satang\" <= \"order\".\"subtotal_satang\")\n);\n",
      "\nCREATE INDEX `order_business_date_status_idx` ON `order` (`business_date`,`status`);",
      "\nCREATE INDEX `order_status_idx` ON `order` (`status`);",
      "\nCREATE INDEX `order_shift_idx` ON `order` (`shift_id`);",
      "\nCREATE UNIQUE INDEX `order_device_id_receipt_no_unique` ON `order` (`device_id`,`receipt_no`);",
      "\nCREATE UNIQUE INDEX `order_device_id_business_date_queue_no_unique` ON `order` (`device_id`,`business_date`,`queue_no`);",
      "\nCREATE TABLE `order_event` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`seq` integer NOT NULL,\n\t`device_id` text,\n\t`chain_id` text NOT NULL,\n\t`chain_seq` integer NOT NULL,\n\t`type` text NOT NULL,\n\t`payload_json` text NOT NULL,\n\t`actor_type` text NOT NULL,\n\t`actor_id` text NOT NULL,\n\t`at` text NOT NULL,\n\t`prev_hash` text NOT NULL,\n\t`hash` text NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `order_event_order_id_seq_unique` ON `order_event` (`order_id`,`seq`);",
      "\nCREATE UNIQUE INDEX `order_event_chain_id_chain_seq_unique` ON `order_event` (`chain_id`,`chain_seq`);",
      "\nCREATE TABLE `order_line` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`line_no` integer NOT NULL,\n\t`variant_id` text NOT NULL,\n\t`sweetness_id` text NOT NULL,\n\t`recipe_id` text,\n\t`product_name` text NOT NULL,\n\t`size_name` text NOT NULL,\n\t`sweetness_name` text NOT NULL,\n\t`unit_price_satang` integer NOT NULL,\n\t`qty` integer NOT NULL,\n\t`line_total_satang` integer NOT NULL,\n\t`unit_cost_satang` integer NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`variant_id`) REFERENCES `product_variant`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`sweetness_id`) REFERENCES `sweetness_level`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`recipe_id`) REFERENCES `recipe`(`id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT \"order_line_qty_positive_ck\" CHECK(\"order_line\".\"qty\" > 0)\n);\n",
      "\nCREATE UNIQUE INDEX `order_line_order_id_line_no_unique` ON `order_line` (`order_id`,`line_no`);",
      "\nCREATE TABLE `order_payment_intent` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`promptpay_payload` text NOT NULL,\n\t`amount_satang` integer NOT NULL,\n\t`expires_at` text NOT NULL,\n\t`slip_image_ref` text,\n\t`customer_claimed_at` text,\n\tFOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `order_payment_intent_order_idx` ON `order_payment_intent` (`order_id`);",
      "\nCREATE TABLE `payment` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`method` text NOT NULL,\n\t`amount_satang` integer NOT NULL,\n\t`tendered_satang` integer,\n\t`change_satang` integer,\n\t`reference` text,\n\t`verify_status` text NOT NULL,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT \"payment_amount_positive_ck\" CHECK(\"payment\".\"amount_satang\" > 0)\n);\n",
      "\nCREATE INDEX `payment_order_idx` ON `payment` (`order_id`);",
      "\nCREATE TABLE `shift` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`device_id` text NOT NULL,\n\t`business_date` text NOT NULL,\n\t`status` text NOT NULL,\n\t`opened_by` text NOT NULL,\n\t`opened_at` text NOT NULL,\n\t`opening_float_satang` integer NOT NULL,\n\t`closed_by` text,\n\t`closed_at` text,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`opened_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`closed_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `shift_open_uq` ON `shift` (`device_id`) WHERE status = 'open';",
      "\nCREATE TABLE `z_report` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`shift_id` text NOT NULL,\n\t`snapshot_json` text NOT NULL,\n\t`hash` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`shift_id`) REFERENCES `shift`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `z_report_shift_id_unique` ON `z_report` (`shift_id`);",
      "\nCREATE TABLE `audit_log` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`entity` text NOT NULL,\n\t`entity_id` text NOT NULL,\n\t`action` text NOT NULL,\n\t`before_json` text,\n\t`after_json` text,\n\t`actor_user_id` text,\n\t`at` text NOT NULL\n);\n",
      "\nCREATE INDEX `audit_log_entity_idx` ON `audit_log` (`entity`,`entity_id`);",
      "\nCREATE TABLE `outbox` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`table_name` text NOT NULL,\n\t`row_json` text NOT NULL,\n\t`idempotency_key` text NOT NULL,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`attempts` integer NOT NULL,\n\t`last_error` text,\n\t`sent_at` text,\n\t`dead_at` text\n);\n",
      "\nCREATE UNIQUE INDEX `outbox_idempotency_key_unique` ON `outbox` (`idempotency_key`);",
      "\nCREATE INDEX `outbox_pending_idx` ON `outbox` (`created_at`) WHERE status = 'pending';",
      "\nCREATE TABLE `sync_state` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`value` text NOT NULL\n);\n"
    ],
    "bps": true,
    "folderMillis": 1789724559640,
    "hash": "f09a46b1485e2ad61c6a5001089a562b347cf45df8a9fb64515b2f97667e7b62"
  },
  {
    "tag": "0001_append_only",
    "sql": [
      "-- Custom SQL migration file, put your code below! --\n-- M6: ledger tables are append-only at the DB level (spec §3.3 stock_movement, §3.4 order_event, §3.5 cash_movement\n-- and z_report). Any UPDATE or DELETE aborts. NOTE: SQLite drops a table's triggers with the table, so a future\n-- migration that recreates one of these tables must recreate its triggers too — test/triggers.test.ts checks\n-- the final state after all migrations.\nCREATE TRIGGER `stock_movement_no_update` BEFORE UPDATE ON `stock_movement` BEGIN SELECT RAISE(ABORT, 'stock_movement is append-only: UPDATE rejected'); END;\n",
      "\nCREATE TRIGGER `stock_movement_no_delete` BEFORE DELETE ON `stock_movement` BEGIN SELECT RAISE(ABORT, 'stock_movement is append-only: DELETE rejected'); END;\n",
      "\nCREATE TRIGGER `order_event_no_update` BEFORE UPDATE ON `order_event` BEGIN SELECT RAISE(ABORT, 'order_event is append-only: UPDATE rejected'); END;\n",
      "\nCREATE TRIGGER `order_event_no_delete` BEFORE DELETE ON `order_event` BEGIN SELECT RAISE(ABORT, 'order_event is append-only: DELETE rejected'); END;\n",
      "\nCREATE TRIGGER `cash_movement_no_update` BEFORE UPDATE ON `cash_movement` BEGIN SELECT RAISE(ABORT, 'cash_movement is append-only: UPDATE rejected'); END;\n",
      "\nCREATE TRIGGER `cash_movement_no_delete` BEFORE DELETE ON `cash_movement` BEGIN SELECT RAISE(ABORT, 'cash_movement is append-only: DELETE rejected'); END;\n",
      "\nCREATE TRIGGER `z_report_no_update` BEFORE UPDATE ON `z_report` BEGIN SELECT RAISE(ABORT, 'z_report is append-only: UPDATE rejected'); END;\n",
      "\nCREATE TRIGGER `z_report_no_delete` BEFORE DELETE ON `z_report` BEGIN SELECT RAISE(ABORT, 'z_report is append-only: DELETE rejected'); END;\n"
    ],
    "bps": true,
    "folderMillis": 1789724617156,
    "hash": "5b813033396dbd1fd39c0207a3389dbc4ce7b19eb888810e643a2b89de4591ff"
  },
  {
    "tag": "0002_stock_adjustment",
    "sql": [
      "CREATE TABLE `stock_adjustment` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`business_date` text NOT NULL,\n\t`reason_code` text NOT NULL,\n\t`reason` text NOT NULL,\n\t`detail_json` text,\n\t`device_id` text,\n\t`created_by` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action\n);\n"
    ],
    "bps": true,
    "folderMillis": 1789977341065,
    "hash": "d325bdc7737e454a58830037b9999d0e3b6225da9eb3bcbf0c7ed642e5993b49"
  },
  {
    "tag": "0003_block2_central_catalog",
    "sql": [
      "CREATE TABLE `order_item` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`order_id` text NOT NULL,\n\t`line_no` integer NOT NULL,\n\t`menu_code` text NOT NULL,\n\t`menu_name_th` text NOT NULL,\n\t`size` text NOT NULL,\n\t`sweetness` text NOT NULL,\n\t`milk` text NOT NULL,\n\t`grade` text,\n\t`qty` integer NOT NULL,\n\t`unit_price_satang` integer NOT NULL,\n\t`discount_per_cup_satang` integer NOT NULL,\n\t`discount_reason` text,\n\t`promotion_id` text,\n\t`line_total_satang` integer NOT NULL,\n\tFOREIGN KEY (`order_id`) REFERENCES `order`(`id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT \"order_item_qty_positive_ck\" CHECK(\"order_item\".\"qty\" > 0),\n\tCONSTRAINT \"order_item_money_nonneg_ck\" CHECK(\"order_item\".\"unit_price_satang\" >= 0 and \"order_item\".\"discount_per_cup_satang\" >= 0 and \"order_item\".\"line_total_satang\" >= 0)\n);\n",
      "\nCREATE UNIQUE INDEX `order_item_order_id_line_no_unique` ON `order_item` (`order_id`,`line_no`);",
      "\nCREATE TABLE `dayo_catalog` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`catalog_version` integer NOT NULL,\n\t`catalog_json` text NOT NULL,\n\t`staff_json` text NOT NULL,\n\t`client_json` text,\n\t`fetched_at` text NOT NULL,\n\tCONSTRAINT \"dayo_catalog_single_row_ck\" CHECK(\"dayo_catalog\".\"id\" = 'current')\n);\n",
      "\nPRAGMA foreign_keys=OFF;",
      "\nCREATE TABLE `__new_order` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`origin` text NOT NULL,\n\t`device_id` text,\n\t`receipt_no` text,\n\t`queue_no` integer,\n\t`business_date` text NOT NULL,\n\t`shift_id` text,\n\t`channel_id` text,\n\t`customer_id` text,\n\t`status` text NOT NULL,\n\t`subtotal_satang` integer NOT NULL,\n\t`discount_satang` integer NOT NULL,\n\t`total_satang` integer NOT NULL,\n\t`vat_satang` integer NOT NULL,\n\t`cost_satang` integer NOT NULL,\n\t`note` text,\n\t`created_by_type` text NOT NULL,\n\t`created_by_id` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`paid_at` text,\n\t`ready_at` text,\n\t`voided_at` text,\n\t`sold_at` text,\n\t`catalog_version` integer,\n\t`channel_code` text,\n\t`payment_code` text,\n\t`pricing_json` text,\n\t`excluded_at` text,\n\t`central_order_no` text,\n\t`central_computed_total_satang` integer,\n\t`central_amount_mismatch` integer,\n\t`central_duplicate_of_json` text,\n\tFOREIGN KEY (`device_id`) REFERENCES `device`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`shift_id`) REFERENCES `shift`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`channel_id`) REFERENCES `channel`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`customer_id`) REFERENCES `customer`(`id`) ON UPDATE no action ON DELETE no action,\n\tCONSTRAINT \"order_subtotal_nonneg_ck\" CHECK(\"__new_order\".\"subtotal_satang\" >= 0),\n\tCONSTRAINT \"order_discount_nonneg_ck\" CHECK(\"__new_order\".\"discount_satang\" >= 0),\n\tCONSTRAINT \"order_total_nonneg_ck\" CHECK(\"__new_order\".\"total_satang\" >= 0),\n\tCONSTRAINT \"order_discount_le_subtotal_ck\" CHECK(\"__new_order\".\"discount_satang\" <= \"__new_order\".\"subtotal_satang\"),\n\tCONSTRAINT \"order_channel_ck\" CHECK(\"__new_order\".\"channel_id\" is not null or \"__new_order\".\"channel_code\" is not null)\n);\n",
      "\n-- drizzle-kit listed the 10 block-2 columns in the SELECT too, but the old `order` does not have them: copy the 22\n-- existing columns only; the new ones start NULL.\nINSERT INTO `__new_order`(\"id\", \"origin\", \"device_id\", \"receipt_no\", \"queue_no\", \"business_date\", \"shift_id\", \"channel_id\", \"customer_id\", \"status\", \"subtotal_satang\", \"discount_satang\", \"total_satang\", \"vat_satang\", \"cost_satang\", \"note\", \"created_by_type\", \"created_by_id\", \"created_at\", \"paid_at\", \"ready_at\", \"voided_at\") SELECT \"id\", \"origin\", \"device_id\", \"receipt_no\", \"queue_no\", \"business_date\", \"shift_id\", \"channel_id\", \"customer_id\", \"status\", \"subtotal_satang\", \"discount_satang\", \"total_satang\", \"vat_satang\", \"cost_satang\", \"note\", \"created_by_type\", \"created_by_id\", \"created_at\", \"paid_at\", \"ready_at\", \"voided_at\" FROM `order`;",
      "\nDROP TABLE `order`;",
      "\nALTER TABLE `__new_order` RENAME TO `order`;",
      "\nPRAGMA foreign_keys=ON;",
      "\nCREATE INDEX `order_business_date_status_idx` ON `order` (`business_date`,`status`);",
      "\nCREATE INDEX `order_status_idx` ON `order` (`status`);",
      "\nCREATE INDEX `order_shift_idx` ON `order` (`shift_id`);",
      "\nCREATE UNIQUE INDEX `order_device_id_receipt_no_unique` ON `order` (`device_id`,`receipt_no`);",
      "\nCREATE UNIQUE INDEX `order_device_id_business_date_queue_no_unique` ON `order` (`device_id`,`business_date`,`queue_no`);",
      "\nALTER TABLE `outbox` ADD `next_attempt_at` text;",
      "\nALTER TABLE `outbox` ADD `parent_key` text;",
      "\nALTER TABLE `outbox` ADD `result_json` text;",
      "\nCREATE INDEX `outbox_parent_idx` ON `outbox` (`parent_key`);"
    ],
    "bps": true,
    "folderMillis": 1790354703240,
    "hash": "8539f1a2c6204a28f952422d90deb606e1a55be16c0ef49ddbe278beb75cd79f"
  },
  {
    "tag": "0004_block2_outbox_local_only",
    "sql": [
      "-- block 2 (spec 04 §6.1, ruling R7): every row queued before block 2 used the plan-3/4 row format, which dayo's\n-- /v1/pos/push does not accept. They stay on the tablet as local records only and are never sent.\nUPDATE `outbox` SET `status` = 'local_only' WHERE `status` IN ('pending', 'dead');\n",
      "\nCREATE TRIGGER `order_item_no_update` BEFORE UPDATE ON `order_item` BEGIN SELECT RAISE(ABORT, 'order_item is append-only: UPDATE rejected'); END;\n",
      "\nCREATE TRIGGER `order_item_no_delete` BEFORE DELETE ON `order_item` BEGIN SELECT RAISE(ABORT, 'order_item is append-only: DELETE rejected'); END;\n"
    ],
    "bps": true,
    "folderMillis": 1790354704892,
    "hash": "e54f944203567ff6aed14323822c5ca830c7e27ff0e3362da36510d5d7fad302"
  },
  {
    "tag": "0005_order_central_dayo_edit",
    "sql": [
      "-- block 2 (ADR-0050): dayo's E3 dayo_edit for this bill — the owner's latest edit/cancel on the dayo web, null = none.\n-- Display only on the tablet: total_satang, payment and status stay what was collected (spec 04 §4.6 · O1 pending).\nALTER TABLE `order` ADD `central_dayo_edit_json` text;\n"
    ],
    "bps": true,
    "folderMillis": 1790357711385,
    "hash": "34c7b939d3682f17660d8bb8ae16bfe803df4de9396883d3e82c620c44f3ac78"
  },
  {
    "tag": "0006_block3_shift_cash",
    "sql": [
      "ALTER TABLE `cash_count` ADD `counted_at` text;",
      "\nALTER TABLE `cash_count` ADD `includes_bot_cash` integer DEFAULT false NOT NULL;",
      "\nCREATE UNIQUE INDEX `cash_count_shift_uq` ON `cash_count` (`shift_id`);",
      "\nALTER TABLE `order` ADD `off_catalog_at` text;",
      "\nALTER TABLE `order` ADD `central_mismatch_json` text;",
      "\nALTER TABLE `shift` ADD `counted_at` text;",
      "\nALTER TABLE `shift` ADD `sync_mode` text DEFAULT 'local_only' NOT NULL;",
      "\nCREATE UNIQUE INDEX `shift_counting_uq` ON `shift` (`device_id`) WHERE status = 'counting';",
      "\n-- block 3 (spec 04 §4.10 rule 4 · ruling R1): every shift from before this migration never reached dayo — local_only for good.\nUPDATE `shift` SET `sync_mode` = 'local_only';\n",
      "\nUPDATE `shift` SET `counted_at` = (SELECT min(`created_at`) FROM `cash_count` WHERE `cash_count`.`shift_id` = `shift`.`id`) WHERE `status` = 'closed';\n",
      "\nUPDATE `cash_count` SET `counted_at` = `created_at`;\n",
      "\nCREATE TRIGGER `cash_count_no_update` BEFORE UPDATE ON `cash_count` BEGIN SELECT RAISE(ABORT, 'cash_count is append-only: UPDATE rejected'); END;\n",
      "\nCREATE TRIGGER `cash_count_no_delete` BEFORE DELETE ON `cash_count` BEGIN SELECT RAISE(ABORT, 'cash_count is append-only: DELETE rejected'); END;\n",
      "\nCREATE TRIGGER `shift_status_forward_only` BEFORE UPDATE OF `status` ON `shift`\nWHEN NEW.`status` NOT IN ('open', 'counting', 'counted', 'closed')\n  OR (CASE NEW.`status` WHEN 'open' THEN 0 WHEN 'counting' THEN 1 WHEN 'counted' THEN 2 ELSE 3 END) < (CASE OLD.`status` WHEN 'open' THEN 0 WHEN 'counting' THEN 1 WHEN 'counted' THEN 2 ELSE 3 END)\n  OR (NEW.`status` IN ('counting', 'counted', 'closed') AND NEW.`counted_at` IS NULL)\nBEGIN SELECT RAISE(ABORT, 'shift.status only moves forward: open → counting → counted → closed; counting, counted and closed need counted_at (D101)'); END;\n",
      "\nCREATE TRIGGER `shift_sync_mode_one_way` BEFORE UPDATE OF `sync_mode` ON `shift`\nWHEN NEW.`sync_mode` NOT IN ('central','local_only') OR (OLD.`sync_mode` = 'local_only' AND NEW.`sync_mode` <> 'local_only')\nBEGIN SELECT RAISE(ABORT, 'shift.sync_mode only moves central → local_only (R1 · R19)'); END;\n",
      "\nCREATE TRIGGER `shift_sync_mode_valid` BEFORE INSERT ON `shift` WHEN NEW.`sync_mode` NOT IN ('central','local_only')\nBEGIN SELECT RAISE(ABORT, 'shift.sync_mode must be central or local_only (R1)'); END;\n",
      "\nCREATE TRIGGER `shift_counted_at_once` BEFORE UPDATE OF `counted_at` ON `shift` WHEN OLD.`counted_at` IS NOT NULL AND NEW.`counted_at` IS NOT OLD.`counted_at`\nBEGIN SELECT RAISE(ABORT, 'shift.counted_at is set once (D101)'); END;\n",
      "\nCREATE TRIGGER `cash_movement_open_shift_only` BEFORE INSERT ON `cash_movement` WHEN (SELECT `status` FROM `shift` WHERE `id` = NEW.`shift_id`) IS NOT 'open'\nBEGIN SELECT RAISE(ABORT, 'cash_movement needs an open shift (D101: a counted shift takes no more cash movements)'); END;\n",
      "\nCREATE TRIGGER `order_open_shift_only` BEFORE INSERT ON `order` WHEN NEW.`shift_id` IS NOT NULL AND (SELECT `status` FROM `shift` WHERE `id` = NEW.`shift_id`) IS NOT 'open'\nBEGIN SELECT RAISE(ABORT, 'a bill needs an open shift (D101)'); END;\n",
      "\nCREATE TRIGGER `outbox_row_json_frozen` BEFORE UPDATE OF `row_json` ON `outbox` WHEN OLD.`status` IN ('sent', 'closed_off_catalog')\nBEGIN SELECT RAISE(ABORT, 'outbox.row_json is frozen once the row is sent or closed_off_catalog (spec 04 §6.1)'); END;\n"
    ],
    "bps": true,
    "folderMillis": 1790654480696,
    "hash": "5002ef1fa71e94b0e0444b7e84905d33ca3030074bfe232582d86a59b5afe076"
  }
]

/** Tables and triggers that migrateSqlite leaves in a fresh database. */
export const SQLITE_TABLES: readonly string[] = ["audit_log","bom","bom_line","cash_count","cash_movement","category","channel","customer","dayo_catalog","device","discount","equipment","item","item_cost_state","order","order_event","order_item","order_line","order_payment_intent","outbox","payment","price","product","product_variant","production_batch","purchase","purchase_line","purchase_unit","recipe","recipe_line","setting","shift","size","stock_adjustment","stock_count","stock_count_line","stock_movement","sweetness_level","sync_state","user","z_report"]
export const SQLITE_TRIGGERS: readonly string[] = ["cash_count_no_delete","cash_count_no_update","cash_movement_no_delete","cash_movement_no_update","cash_movement_open_shift_only","order_event_no_delete","order_event_no_update","order_item_no_delete","order_item_no_update","order_open_shift_only","outbox_row_json_frozen","shift_counted_at_once","shift_status_forward_only","shift_sync_mode_one_way","shift_sync_mode_valid","stock_movement_no_delete","stock_movement_no_update","z_report_no_delete","z_report_no_update"]
