// ข้อความบนจอทั้งหมดของแอปขาย — แก้คำได้ที่ไฟล์นี้ไฟล์เดียว (e2e อ้าง data-testid ไม่อ้างข้อความ)
export const TH = {
  appName: 'DA-YO POS',
  loading: 'กำลังโหลด…',
  retry: 'ลองใหม่',
  back: 'กลับ',
  cancel: 'ยกเลิก',
  lock: 'ล็อก',
  dbError: 'เปิดฐานข้อมูลในเครื่องไม่ได้',
  dbErrorTwoTabs: 'ถ้าเปิดแอปนี้อยู่ในแท็บหรือหน้าต่างอื่น ให้ปิดอันนั้นก่อนแล้วกดลองใหม่',
  pendingSync: (n: number): string => `ยังไม่ส่งขึ้นเซิร์ฟเวอร์ ${n} รายการ`,
  storageNotPersistent: 'ข้อมูลในเครื่องยังไม่ถูกล็อกไว้ (อาจถูกล้าง) — ติดตั้งแอปลงหน้าจอหลัก',
  errUnexpected: 'เกิดข้อผิดพลาด ลองใหม่อีกครั้ง',
  errorDetail: 'รายละเอียด (สำหรับแก้ปัญหา)',

  setupTitle: 'ตั้งค่าเครื่องครั้งแรก',
  setupDeviceName: 'ชื่อเครื่อง',
  setupDeviceNameDefault: 'แท็บเล็ตหน้าร้าน',
  setupReceiptPrefix: 'อักษรนำหน้าเลขที่บิล (A–Z)',
  setupOwner: (n: number): string => `เจ้าของคนที่ ${n}`,
  setupDisplayName: 'ชื่อที่แสดง',
  setupPin: 'PIN ตัวเลข 4–6 หลัก',
  setupPinConfirm: 'ยืนยัน PIN อีกครั้ง',
  setupPromptPayId: 'หมายเลขพร้อมเพย์ (เบอร์มือถือ 10 หลัก / เลขบัตร 13 หลัก / e-Wallet 15 หลัก)',
  setupSave: 'บันทึกและเริ่มใช้งาน',

  loginTitle: 'ใครกำลังใช้งาน',
  loginEnterPin: (name: string): string => `ใส่ PIN ของ ${name}`,

  shiftOpenTitle: 'เปิดกะ',
  shiftOpeningFloat: 'เงินทอนในลิ้นชักตอนเปิดกะ (บาท)',
  shiftOpen: 'เปิดกะ',

  tabBestSellers: 'ขายดี',
  cart: 'ตะกร้า',
  cartEmpty: 'ยังไม่มีรายการ',
  subtotal: 'รวม',
  discount: 'ส่วนลด',
  total: 'ยอดสุทธิ',
  payCash: 'เงินสด',
  payQr: 'QR พร้อมเพย์',
  size: 'ขนาด',
  sweetness: 'ความหวาน',
  sweetShort: 'หวาน',
  addToCart: 'เพิ่มลงตะกร้า',
  clearCart: 'ล้างตะกร้า',
  noPrice: 'ไม่มีราคา',
  orders: 'บิลวันนี้',

  discountTitle: 'ส่วนลดท้ายบิล',
  discountAmount: 'จำนวนเงิน (บาท)',
  discountReason: 'เหตุผล',
  discountApply: 'ใช้ส่วนลด',
  discountRemove: 'ลบส่วนลด',

  cashTitle: 'รับเงินสด',
  exact: 'พอดี',
  tendered: 'รับเงินมา (บาท)',
  change: 'เงินทอน',
  confirmCash: 'ยืนยันรับเงิน',

  qrTitle: 'สแกนจ่ายด้วยพร้อมเพย์',
  qrReceived: 'ได้รับเงินแล้ว',

  queue: 'คิว',
  receiptNo: 'เลขที่บิล',
  newSale: 'ขายต่อ',

  statusPaid: 'ชำระแล้ว',
  statusVoided: 'ยกเลิกแล้ว',
  methodCash: 'เงินสด',
  methodPromptPay: 'พร้อมเพย์',
  noOrders: 'ยังไม่มีบิลในกะนี้',
  lines: 'รายการ',
  payment: 'การชำระ',
  events: 'ประวัติเหตุการณ์',
  voidOrder: 'ยกเลิกบิล',

  voidTitle: (receiptNo: string): string => `ยกเลิกบิล ${receiptNo}`,
  voidReason: 'เหตุผล',
  voidReasonPresets: ['ลูกค้าเปลี่ยนใจ', 'กดผิดเมนู', 'ทำผิดสูตร'], // 3 preset buttons + free text (D48 Q3-14)
  voidMadeQuestion: 'ทำเครื่องดื่มไปแล้วหรือยัง',
  voidMadeYes: 'ทำแล้ว (ทิ้งเป็นของเสีย)',
  voidMadeNo: 'ยังไม่ทำ (คืนวัตถุดิบเข้าสต็อก)',
  voidCashRefund: (amount: string): string => `คืนเงินสด ${amount} จากลิ้นชัก`,
  voidQrRefundRef: 'เลขอ้างอิงการโอนคืน',
  voidApprover: 'เจ้าของที่อนุมัติ',
  voidConfirm: 'ยืนยันยกเลิกบิล',

  errDbOpenFailed: 'เปิดฐานข้อมูลในเครื่องไม่ได้',
  errNeedsSetup: 'เครื่องนี้ยังไม่ได้ตั้งค่า',
  errAlreadySetUp: 'เครื่องนี้ตั้งค่าไปแล้ว',
  errBadInput: 'ข้อมูลไม่ถูกต้อง',
  errPinFormat: 'PIN ต้องเป็นตัวเลข 4–6 หลัก',
  errPinMismatch: 'PIN สองช่องไม่ตรงกัน',
  errPinWrong: 'PIN ไม่ถูกต้อง',
  errPinLocked: 'ใส่ PIN ผิดหลายครั้ง — รอสักครู่แล้วลองใหม่',
  errPinLockedFor: (seconds: number): string => `ใส่ PIN ผิดหลายครั้ง — ลองใหม่ใน ${seconds} วินาที`,
  errNotOwner: 'ต้องเป็นเจ้าของร้านเท่านั้น',
  errNoOpenShift: 'ยังไม่ได้เปิดกะ',
  errShiftAlreadyOpen: 'มีกะเปิดอยู่แล้ว',
  errEmptyCart: 'ตะกร้าว่าง',
  errNoPrice: 'เมนูนี้ยังไม่มีราคา ขายไม่ได้',
  errNoRecipe: 'เมนูนี้ยังไม่มีสูตร ขายไม่ได้',
  errTenderTooLow: 'รับเงินน้อยกว่ายอด',
  errDiscountTooBig: 'ส่วนลดต้องน้อยกว่ายอดรวม',
  errPriceChanged: 'ราคาเปลี่ยนแล้ว — กำลังปรับราคาในตะกร้า',
  errReasonRequired: 'ต้องใส่เหตุผล',
  errNoPromptPayId: 'ยังไม่ได้ตั้งหมายเลขพร้อมเพย์',
  errOrderNotFound: 'ไม่พบบิล',
  errVoidNotAllowed: 'ยกเลิกได้เฉพาะบิลที่ชำระแล้วในกะที่เปิดอยู่',
  errChooseMade: 'เลือกก่อนว่าทำเครื่องดื่มไปแล้วหรือยัง',
  errRefundRefRequired: 'ต้องใส่เลขอ้างอิงการโอนคืน',
} as const
