// ข้อความบนจอทั้งหมดของแอปขาย — แก้คำได้ที่ไฟล์นี้ไฟล์เดียว (e2e อ้าง data-testid ไม่อ้างข้อความ)
export const TH = {
  appName: 'DA-YO POS',
  loading: 'กำลังโหลด…',
  retry: 'ลองใหม่',
  back: 'กลับ',
  cancel: 'ยกเลิก',
  lock: 'ล็อก',
  dbError: 'เปิดฐานข้อมูลในเครื่องไม่ได้',
  dbErrorTwoTabs: 'ถ้าเปิดแอปนี้อยู่ในแท็บหรือหน้าต่างอื่น ให้ปิดอันนั้นก่อนแล้วกดลองใหม่',
  pendingSync: (n: number): string => `ยังไม่ส่งขึ้นเซิร์ฟเวอร์ ${n} รายการ`,
  storageNotPersistent: 'ข้อมูลในเครื่องยังไม่ถูกล็อกไว้ (อาจถูกล้าง) — ติดตั้งแอปลงหน้าจอหลัก',
  errUnexpected: 'เกิดข้อผิดพลาด ลองใหม่อีกครั้ง',

  // Task 17 — ตั้งเครื่องด้วยกุญแจ dayo (spec 04 §7 ข้อ 1, §6.5, §6.6, §6.9)
  setupTitle: 'ตั้งเครื่องขาย',
  setupLinkTitle: 'เชื่อมเครื่องนี้กับระบบกลาง',
  setupReceiptPrefix: 'อักษรนำหน้าเลขที่บิล (A–Z)',
  setupPin: 'PIN ตัวเลข 4–6 หลัก',
  setupPinConfirm: 'ยืนยัน PIN อีกครั้ง',
  setupPromptPayId: 'หมายเลขพร้อมเพย์ (เบอร์มือถือ 10 หลัก / เลขบัตร 13 หลัก / e-Wallet 15 หลัก)',
  setupSave: 'บันทึกและเริ่มใช้งาน',
  setupBaseUrl: 'ที่อยู่ระบบกลาง (dayo)',
  setupApiKey: 'กุญแจเครื่อง (API key)',
  setupScan: 'สแกน QR',
  setupProbe: 'ทดสอบกุญแจ',
  setupConnectedTo: (name: string): string => `เชื่อมกับ: ${name}`,
  pricingMismatchSetup: 'ตัวคิดราคาในเครื่องไม่ตรงกับระบบกลาง — ขายได้ แต่แจ้งทีม POS',
  setupChooseOwner: 'เลือกเจ้าของร้าน (จากระบบกลาง)',
  setupLegacyUser: 'เจ้าของเดิมของเครื่องนี้',
  setupLegacyPin: 'PIN เจ้าของเดิม (อนุมัติการเชื่อมเครื่อง)',
  persistOk: 'เก็บข้อมูลถาวร: ได้',
  persistNo: 'เก็บข้อมูลถาวร: ไม่ได้ — อย่าล้างข้อมูลเบราว์เซอร์',
  setupContinue: 'ไปหน้าขาย',
  errChooseOwner: 'เลือกเจ้าของก่อน',
  // spec §7 ข้อ 1 "สแกนหรือวาง" — quality review (fix round 1): the browser's own text (permission wording, "no
  // barcode" wording) never reaches the screen; every scan failure gets its own Thai message instead.
  scanCameraDenied: 'เปิดกล้องไม่ได้ — อนุญาตให้แอปใช้กล้องแล้วลองใหม่ หรือวางกุญแจด้วยตัวเอง',
  scanNoCode: 'ไม่พบ QR โค้ดในกล้อง — ลองใหม่ หรือวางกุญแจด้วยตัวเอง',
  dayoBadKey: 'กุญแจไม่ถูกต้องหรือถูกยกเลิก',
  dayoNoScope: 'กุญแจนี้ไม่มีสิทธิ์อ่านเมนู/พนักงาน',
  dayoApiOff: 'ระบบกลางปิด API อยู่',
  dayoUnreachable: 'ติดต่อระบบกลางไม่ได้ — ต้องออนไลน์ตอนตั้งเครื่อง',
  dayoBadResponse: 'ระบบกลางตอบรูปแบบที่เครื่องนี้อ่านไม่ได้ — แจ้งทีม POS',
  // "ปรับตาม dayo" (สเปก §4.4 ข้อ 6 · §6.6): the value dayo actually sent, so the owner can check the tablet's key
  // against the right device on the dayo web instead of guessing from a shape description.
  dayoReceiptNoInvalid: (value: string): string => `เลขใบเสร็จล่าสุดที่ระบบกลางจำไว้ (${value}) ไม่ใช่รูปแบบของแท็บเล็ต — ให้เจ้าของตรวจกุญแจเครื่องบนเว็บ dayo`,
  noCatalog: 'ยังไม่มีเมนูจากระบบกลาง — ต่อเน็ตแล้วกด "ส่งตอนนี้"',
  // ruling N2 + controller ruling R1 (security): recovery only ever targets the address already stored on this
  // tablet — a working owner PIN still goes through "เปลี่ยนกุญแจ" (replaceApiKey), not this screen.
  recoveryNotAllowed: "กู้สิทธิ์เจ้าของไม่ได้ตอนนี้ — ถ้ายังมีเจ้าของที่ใช้ PIN ได้ ให้ใช้ 'เปลี่ยนกุญแจ' ที่หน้าสถานะ · กุญแจใหม่ต้องเป็นของระบบกลางเดิม",
  keyNotNew: 'นี่คือกุญแจเดิม — ออกกุญแจใหม่บนเว็บ',
  oldKeyStillActive: 'ยังไม่ได้เพิกถอนกุญแจเก่าบนเว็บ — เพิกถอนก่อนแล้วกดอีกครั้ง',

  needsPinTitle: 'ต้องตั้ง PIN ก่อนใช้',
  ownerRecoveryBanner: 'ไม่มีเจ้าของที่ใช้งานได้บนเครื่องนี้',
  ownerRecoveryButton: 'เชื่อมใหม่ด้วยคีย์ใหม่',
  ownerRecoveryTitle: 'เชื่อมใหม่ด้วยคีย์ใหม่',
  ownerRecoveryStep1: '1) ล็อกอินเว็บ dayo ด้วย LINE ในฐานะเจ้าของ แล้วออกกุญแจใหม่ที่ /settings/api-clients',
  ownerRecoveryStep2: '2) เพิกถอนกุญแจเก่าของเครื่องนี้บนเว็บ',
  ownerRecoveryStep3: '3) สแกน/วางกุญแจใหม่ แล้วทดสอบกุญแจ เลือกเจ้าของ และตั้ง PIN',
  // controller ruling R1 (security)
  ownerRecoveryNoAddress: 'เครื่องนี้ไม่มีที่อยู่ระบบกลางที่บันทึกไว้ — ต้องตั้งเครื่องใหม่',

  staffPinTitle: (name: string): string => `ตั้ง PIN ให้ ${name}`,
  staffPinApprover: 'เจ้าของผู้อนุมัติ',
  staffPinApproverPin: 'PIN เจ้าของผู้อนุมัติ',
  staffPinNew: 'PIN ใหม่',
  staffPinNew2: 'ยืนยัน PIN ใหม่',

  loginTitle: 'ใครกำลังใช้งาน',
  loginEnterPin: (name: string): string => `ใส่ PIN ของ ${name}`,

  shiftOpenTitle: 'เปิดกะ',
  shiftOpeningFloat: 'เงินทอนในลิ้นชักตอนเปิดกะ (บาท)',
  shiftOpen: 'เปิดกะ',

  tabAll: 'ทั้งหมด',
  tabBestSellers: 'ขายดี',
  cart: 'ตะกร้า',
  cartEmpty: 'ยังไม่มีรายการ',
  // phone bottom-sheet cart handle (CartPanel)
  cartCups: (n: number): string => (n === 0 ? 'ว่าง' : `${n} แก้ว`),
  cartExpand: 'ดูรายการ ▲',
  cartCollapse: 'ย่อ ▼',
  cartCheck: 'ตะกร้ามีปัญหา — แตะเพื่อดู',
  subtotal: 'รวม',
  discount: 'ส่วนลด',
  total: 'ยอดสุทธิ',
  payCash: 'เงินสด',
  payQr: 'QR พร้อมเพย์',
  size: 'ขนาด',
  sweetness: 'ความหวาน',
  sweetShort: 'หวาน',
  milk: 'นม',
  milkFresh: 'นมสด',
  milkOat: 'นมโอ๊ต',
  grade: 'เกรด',
  addToCart: 'เพิ่มลงตะกร้า',
  clearCart: 'ล้างตะกร้า',
  noPrice: 'ไม่มีราคา',
  orders: 'บิลวันนี้',
  // review I2: the menu, or every size/sweetness of it, disappeared from the catalog (e.g. a 60 s refetch closed the
  // last size while this popup was open) — never a crash, just refuse to add it.
  itemUnavailable: 'เมนูนี้หรือขนาดนี้ไม่มีขายแล้ว — ปิดหน้านี้แล้วเลือกใหม่',

  // Task 18 — ขายด้วยแคตตาล็อกกลาง (spec 04 §4.4, §5.1, §6.5)
  channel: 'ช่องทางขาย',
  promotions: 'โปรโมชัน',
  promoSkip: 'ไม่ใช้',
  promoUnskip: 'ใช้โปรนี้',
  noPromotions: 'ไม่ใช้โปรทั้งบิล',
  promoCode: 'รหัสโปรโมชัน',
  catalogChanged: 'เมนู/ราคาจากระบบกลางเปลี่ยน — คิดราคาใหม่แล้ว',
  priceChangedConfirm: 'ตรวจยอดใหม่แล้วกดยืนยัน',

  discountTitle: 'ส่วนลดท้ายบิล',
  discountAmount: 'จำนวนเงิน (บาท)',
  discountReason: 'เหตุผล',
  discountApply: 'ใช้ส่วนลด',
  discountRemove: 'ลบส่วนลด',

  cashTitle: 'รับเงินสด',
  exact: 'พอดี',
  tendered: 'รับเงินมา (บาท)',
  change: 'เงินทอน',
  confirmCash: 'ยืนยันรับเงิน',

  qrTitle: 'สแกนจ่ายด้วยพร้อมเพย์',
  qrReceived: 'ได้รับเงินแล้ว',

  priceChanged: (from: string, to: string): string => `ราคาเปลี่ยน: ยอดเดิม ${from} → ยอดใหม่ ${to} — ตรวจยอดแล้วกดยืนยันอีกครั้ง`,
  qrRescan: 'ให้ลูกค้าสแกน QR ใหม่ที่ยอดใหม่',

  queue: 'คิว',
  receiptNo: 'เลขที่บิล',
  newSale: 'ขายต่อ',

  statusPaid: 'ชำระแล้ว',
  statusVoided: 'ยกเลิกแล้ว',
  methodCash: 'เงินสด',
  methodPromptPay: 'พร้อมเพย์',
  noOrders: 'ยังไม่มีบิลในกะนี้',
  lines: 'รายการ',
  payment: 'การชำระ',
  events: 'ประวัติเหตุการณ์',
  voidButton: 'ยกเลิกบิล',

  voidTitle: (receiptNo: string): string => `ยกเลิกบิล ${receiptNo}`,
  voidReason: 'เหตุผล',
  voidReasonPresets: ['ลูกค้าเปลี่ยนใจ', 'กดผิดเมนู', 'ทำผิดสูตร'], // 3 preset buttons + free text (D48 Q3-14)
  voidMadeQuestion: 'ทำเครื่องดื่มไปแล้วหรือยัง',
  voidMadeYes: 'ทำแล้ว (ทิ้งเป็นของเสีย)',
  voidMadeNo: 'ยังไม่ทำ (คืนวัตถุดิบเข้าสต็อก)',
  voidCashRefund: (amount: string): string => `คืนเงินสด ${amount} จากลิ้นชัก`,
  voidQrRefundRef: 'เลขอ้างอิงการโอนคืน',
  voidApprover: 'เจ้าของที่อนุมัติ',
  voidConfirm: 'ยืนยันยกเลิกบิล',

  errDbOpenFailed: 'เปิดฐานข้อมูลในเครื่องไม่ได้',
  errNeedsSetup: 'เครื่องนี้ยังไม่ได้ตั้งค่า',
  errAlreadySetUp: 'เครื่องนี้ตั้งค่าไปแล้ว',
  errBadInput: 'ข้อมูลไม่ถูกต้อง',
  errPinFormat: 'PIN ต้องเป็นตัวเลข 4–6 หลัก',
  errPinMismatch: 'PIN สองช่องไม่ตรงกัน',
  errPinWrong: 'PIN ไม่ถูกต้อง',
  errPinLocked: 'ใส่ PIN ผิดหลายครั้ง — รอสักครู่แล้วลองใหม่',
  errPinLockedFor: (seconds: number): string => `ใส่ PIN ผิดหลายครั้ง — ลองใหม่ใน ${seconds} วินาที`,
  errNotOwner: 'ต้องเป็นเจ้าของร้านเท่านั้น',
  errNoOpenShift: 'ยังไม่ได้เปิดกะ',
  errShiftAlreadyOpen: 'มีกะเปิดอยู่แล้ว',
  errEmptyCart: 'ตะกร้าว่าง',
  errNoPrice: 'เมนูนี้ยังไม่มีราคา ขายไม่ได้',
  errNoRecipe: 'เมนูนี้ยังไม่มีสูตร ขายไม่ได้',
  errTenderTooLow: 'รับเงินน้อยกว่ายอด',
  errDiscountTooBig: 'ส่วนลดต้องน้อยกว่ายอดรวม',
  // minor (review round 1): DiscountDialog's own message when the cart cannot be priced yet at all (no catalog, or a
  // CartError) — distinct from errDiscountTooBig, which means the cart CAN be priced but this amount is too big.
  errCartNotPriced: 'ยังคิดราคาตะกร้าไม่ได้ตอนนี้ — ลองใหม่อีกครั้ง',
  errPriceChanged: 'ราคาเปลี่ยนแล้ว — กำลังปรับราคาในตะกร้า',
  errReasonRequired: 'ต้องใส่เหตุผล',
  errNoPromptPayId: 'ยังไม่ได้ตั้งหมายเลขพร้อมเพย์',
  errOrderNotFound: 'ไม่พบบิล',
  errVoidNotAllowed: 'ยกเลิกได้เฉพาะบิลที่ชำระแล้วในกะที่เปิดอยู่',
  errChooseMade: 'เลือกก่อนว่าทำเครื่องดื่มไปแล้วหรือยัง',
  errRefundRefRequired: 'ต้องใส่เลขอ้างอิงการโอนคืน',
  // Q3b-17 · D54: the close screen clears the count when this comes back — the drawer is counted again, blind, against the new figures.
  errShiftChanged: 'ยอดในกะเปลี่ยนระหว่างนับเงิน — ระบบล้างจำนวนที่นับไว้แล้ว กรุณานับเงินในลิ้นชักใหม่อีกครั้ง',
  errVarianceReasonRequired: 'เงินขาด/เกินเกินเกณฑ์ ต้องใส่เหตุผล',
  errZNotFound: 'ไม่พบรายงาน Z',
  errBackupFailed: 'สำรองไฟล์ไม่สำเร็จ ลองใหม่อีกครั้ง',
  errZChainBroken: 'รายงาน Z ใบก่อนหน้าถูกแก้ไขหรือไฟล์เสีย (ลายเซ็นไม่ตรง) — เจ้าของกรอก PIN อีกครั้งเพื่อรับทราบ แล้วปิดกะต่อได้ (Z ใบนี้จะมีป้ายเตือนถาวร)',
  // block 3 shifts/cash/Z (spec 04 §6.4, §6.8, §7 ข้อ 5–6 · D97)
  errCountPending: 'กะก่อนหน้านับเงินแล้วแต่ยังไม่ยืนยัน — ยืนยันการนับก่อนเปิดกะใหม่',
  errShiftNotCounting: 'กะนี้ไม่ได้อยู่ระหว่างนับเงิน — กลับไปหน้ากะแล้วลองใหม่',
  errZNotReady: 'ยังออกใบปิดกะนี้ไม่ได้ — ต้องออกใบปิดกะของกะก่อนหน้าก่อน',
  errBotCashRequired: 'ต้องดึงบิลเงินสดจากบอทก่อนออกใบปิดกะ — ต่ออินเทอร์เน็ตแล้วลองใหม่',
  errZTooLarge: 'กะนี้มีรายการมากเกินกว่าที่ใบปิดกะส่งได้ — แจ้งทีม POS',
  errOffCatalogNotPossible: 'บิลนี้ปิดเป็นบิลนอกแคตตาล็อกไม่ได้ — ใช้ "ปิดไว้ในเครื่อง" แทน',
  dayoZStateInvalidGeneric: 'ข้อมูลใบปิดกะล่าสุดจากระบบกลางอ่านไม่ได้ — ให้เจ้าของตรวจกุญแจเครื่องบนเว็บ dayo',
  dayoZStateInvalid: (v: string): string => `ข้อมูลใบปิดกะล่าสุดจากระบบกลางอ่านไม่ได้ (${v}) — ให้เจ้าของตรวจกุญแจเครื่องบนเว็บ dayo`,
  errCountFormat: 'จำนวนต้องเป็นตัวเลขจำนวนเต็ม 0–99999',
  errCountFirst: 'กด "นับเสร็จ" ก่อน',

  // Task 15 — หน้านับเงินใหม่ (D101 · D102 · §6.8): นับเสร็จ → ทบทวน → PIN → ใบปิดกะ (ทันทีหรือรอออนไลน์)
  countFinish: 'นับเสร็จ',
  countExpected: 'เงินสดที่ควรมี',
  countNoBotCash: 'ยังไม่รวมบิลเงินสดจากบอท',
  countBotCash: (n: number): string => `บิลเงินสดจากบอท/เว็บ ${n} ใบ`,
  countFrozen: 'กะนี้หยุดรับขายแล้ว — ขายต่อต้องเปิดกะใหม่',
  countConfirmOnline: 'ยืนยันและออกใบปิดกะ',
  countConfirmOffline: 'ยืนยันการนับ (ใบปิดกะออกเมื่อออนไลน์)',
  countSavedOffline: 'บันทึกการนับแล้ว — ใบปิดกะจะออกเมื่อเชื่อมต่อได้',
  zWaitingBanner: (date: string): string => `ใบปิดกะ ${date} รอออนไลน์`,
  zIssue: 'ออกใบปิดกะ',
  zBotWindow: (after: string, until: string): string => `บิลบอทช่วง ${after} – ${until}`,
  zChainCentral: (n: number): string => `ใบปิดกะใบแรกหลังตั้งเครื่องใหม่ จะต่อเลขจาก Z ${n} ในระบบกลาง — เจ้าของกรอก PIN อีกครั้งเพื่อรับทราบ`,
  zLocalOnly: 'ใบปิดกะนี้เก็บในเครื่องเท่านั้น',
  zCentralContinued: (n: number): string => `ต่อเลขจาก Z ${n} ในระบบกลาง`,
  countPendingGo: 'ไปหน้าทบทวนการนับ',
  zBlockedGo: 'ไปออกใบปิดกะของกะก่อนหน้า',

  // แผน 4
  errPriceJump: 'ราคาบางรายการต่างจากราคาที่รับครั้งก่อนเกิน 10% — ตรวจราคาอีกครั้ง แล้วกด "ยืนยันราคานี้"',
  errCartTooLarge: 'ตะกร้ามีรายการหรือจำนวนแก้วมากเกินไป — ตัดบางรายการออกก่อน',
  errQtyOutOfRange: 'จำนวนแก้วต่อรายการไม่ถูกต้อง',
  errSizeClosed: 'ขนาดนี้ปิดขายแล้ว — ลบหรือแก้บรรทัดนี้ก่อนชำระ',
  errGradeRule: 'เมนูนี้ต้องเลือกเกรด (หรือไม่ต้องเลือกเกรดถ้าไม่ใช่มัตฉะ)',
  // review I5: dayo removed this menu entirely — differs from errSizeClosed (the menu exists, only this size closed).
  errMenuGone: 'เมนูนี้ไม่มีขายแล้ว — ลบบรรทัดนี้ก่อนชำระ',
  // review I4: a bill discount left with a reason still clamps to ฿0 (dayo never goes negative) — the tablet must
  // still refuse to pay a ฿0 bill (D50 Q3-20) and say why, instead of a silent disabled button.
  errBillDiscountTooBig: 'ส่วนลดท้ายบิลมากกว่าหรือเท่ากับยอดรวม — บิลเหลือ 0 บาท ขายไม่ได้ ลดส่วนลดหรือลบบรรทัด',
  errZeroTotal: 'ยอดสุทธิเป็น 0 บาท ขายไม่ได้ — บิลต้องมากกว่า 0 บาท',
  // minor: a line dayo priced some units at ฿0 from a promotion (buy-2-get-1) — shown next to that cart line.
  freeUnits: (n: number): string => `แถม ${n} แก้ว`,
  errStockCountNotOpen: 'ใบนับนี้ปิดไปแล้ว — เปิดหน้านับสต็อกใหม่',
  errOpeningCountIncomplete: 'การนับครั้งแรก (ยอดยกมา) ต้องนับให้ครบทุกรายการ — กรอกรายการที่ยังเหลือ (ของที่ไม่มีให้กรอก 0)',

  // แผน 3b — กะ / X / Z / เงินเข้า-ออก / สำรองไฟล์
  shiftMenu: 'กะ / รายงาน X',
  xTitle: 'รายงาน X (ยอดสด ณ ตอนนี้)',
  xExpectedHidden: 'เงินสดที่ควรมีแสดงหลังนับเงินตอนปิดกะเท่านั้น (นับแบบไม่เห็นยอด)',
  shiftInfo: (date: string, name: string): string => `วันทำการ ${date} · เปิดกะโดย ${name}`,
  quickOpenBadge: 'เปิดกะด่วน',
  salesTitle: 'ยอดขาย',
  receiptCount: 'จำนวนบิล',
  voidCount: 'บิลยกเลิก',
  grossSales: 'ยอดขายรวม (รวมบิลยกเลิก)',
  discounts: 'ส่วนลดรวม',
  voidedSales: 'ยอดบิลยกเลิก',
  netSales: 'ยอดขายสุทธิ',
  cashSales: 'รับเงินสด',
  qrSummaryTitle: 'พร้อมเพย์ (เทียบกับแอปธนาคาร)',
  qrSales: 'รับพร้อมเพย์',
  qrRefunded: 'โอนคืน (บิลยกเลิก)',
  qrNet: 'พร้อมเพย์สุทธิ',
  bankQrTotal: 'ยอดพร้อมเพย์ในแอปธนาคาร (บาท · ไม่บังคับ)',
  bankQrNotEntered: 'ไม่ได้กรอก',
  qrDifference: 'ส่วนต่าง (แอปธนาคาร − พร้อมเพย์สุทธิ)',
  drawerTitle: 'เงินสดในลิ้นชัก',
  openingFloat: 'เงินทอนตั้งต้น',
  voidRefunds: 'คืนเงินบิลยกเลิก',
  paidIn: 'เงินเข้า',
  paidOut: 'จ่ายออก',
  drops: 'นำเงินออกไปเก็บ',
  expectedCash: 'เงินสดที่ควรมี',
  cashMovesTitle: 'เงินเข้า-ออกที่บันทึก',
  voidListTitle: 'บิลที่ยกเลิก',
  noVoids: 'ไม่มีบิลยกเลิก',
  voidWasMade: 'ทำแล้ว (ของเสีย)',
  voidNotMade: 'ยังไม่ทำ (คืนสต็อก)',
  voidApprovedBy: (name: string): string => `อนุมัติโดย ${name}`,
  negativeBasesTitle: 'เบสติดลบ (ลืมบันทึกทำเบส?)',
  noNegativeBases: 'ไม่มีเบสติดลบ',
  pendingAtClose: (n: number): string => `ยังไม่ส่งขึ้นเซิร์ฟเวอร์ ${n} รายการ — ข้อมูลอยู่ในเครื่องและในไฟล์สำรอง`,
  closeShift: 'ปิดกะ',
  closeTitle: 'ปิดกะ — นับเงินในลิ้นชัก',
  denomination: 'ชนิด',
  pieces: 'จำนวน',
  countedTotal: 'นับได้',
  countDone: 'นับเสร็จ ดูส่วนต่าง',
  countEdit: 'แก้จำนวนที่นับ',
  variance: 'ส่วนต่าง (นับได้ − ควรมี)',
  varianceReason: 'เหตุผลเงินขาด/เกิน',
  varianceReasonHint: (limit: string): string => `ขาดหรือเกินมากกว่า ${limit} ต้องใส่เหตุผล`,
  closeApprover: 'เจ้าของที่ยืนยันปิดกะ',
  cartNotEmpty: 'ยังมีรายการค้างในตะกร้า — ขายหรือล้างตะกร้าก่อนปิดกะ',
  // The one warning the close screen shows for Z_CHAIN_BROKEN: the cause in plain words, and — D54 Q3b-16's
  // whole point — that acknowledging lets the shift close anyway, so nobody is ever stuck at closing time.
  zChainAck:
    'Z ใบก่อนหน้าลายเซ็นไม่ตรง (ถูกแก้ไขหรือไฟล์เสีย) — เจ้าของกรอก PIN อีกครั้งเพื่อรับทราบแล้วปิดกะต่อได้ ระบบจะคิดยอดสะสมใหม่จาก Z ทุกใบ และติดป้ายเตือนถาวรใน Z ใบนี้',
  // sits by the PIN pad under the full zChainAck warning — it says what to do now, it does not repeat it (review M1)
  zChainAckPin: 'กรอก PIN อีกครั้งเพื่อยืนยันว่ารับทราบ',
  zTitle: 'รายงาน Z',
  zList: 'Z ย้อนหลัง',
  noZ: 'ยังไม่มีรายงาน Z',
  zClosedAt: (at: string): string => `ปิดกะเมื่อ ${at}`,
  zGrandTotal: 'ยอดขายสุทธิสะสม (grand total)',
  zHashOk: 'ตรวจลายเซ็นแล้ว ข้อมูลไม่ถูกแก้',
  zHashBad: 'ลายเซ็นไม่ตรง — ข้อมูลอาจถูกแก้',
  zUnreadable: 'ข้อมูล Z นี้อ่านไม่ได้/ถูกแก้ไข',
  zChainWarning: 'Z ใบนี้ปิดหลังพบว่า Z ใบก่อนหน้าลายเซ็นไม่ตรง — ยอดสะสมคิดใหม่จาก Z ทุกใบ (เจ้าของรับทราบด้วย PIN แล้ว)',
  zChainWarningShort: 'Z ก่อนหน้าลายเซ็นไม่ตรง',
  zDone: 'เสร็จ',
  backupTitle: 'สำรองไฟล์ฐานข้อมูล',
  backupHint: 'ไฟล์จะลงในโฟลเดอร์ดาวน์โหลดของแท็บเล็ต — ย้ายไปเก็บที่ Google Drive หรือคอมพิวเตอร์ทุกวัน',
  backupNow: 'ดาวน์โหลดไฟล์สำรอง',
  backupNever: 'ยังไม่เคยสำรอง',
  backupLast: (at: string): string => `สำรองล่าสุด ${at}`,
  backupCheckFile: (name: string): string => `ตรวจว่าเห็นไฟล์ ${name} ในโฟลเดอร์ดาวน์โหลดแล้ว จึงกด "บันทึกไฟล์แล้ว"`,
  backupConfirm: 'บันทึกไฟล์แล้ว',
  backupDone: (name: string): string => `ยืนยันไฟล์สำรอง ${name} แล้ว`,
  backupOwnerOnly: 'สำรองไฟล์ได้เฉพาะเจ้าของร้าน (ในไฟล์มี PIN เก็บแบบแฮช (ไม่ใช่รหัสจริง) และหมายเลขพร้อมเพย์ของร้าน)',
  backupDue: 'ปิดกะแล้วแต่ยังไม่ได้ยืนยันไฟล์สำรอง — สำรองแล้วกด "บันทึกไฟล์แล้ว" ก่อนปิดเครื่อง',
  shiftStale: (date: string): string => `กะของวันที่ ${date} ยังไม่ปิด — ปิดกะก่อนเริ่มวันใหม่`,
  quickOpen: 'เปิดกะด่วน (เงินทอน 0 · เจ้าของเท่านั้น)',
  cashMove: 'เงินเข้า-ออก',
  cashMoveTitle: 'บันทึกเงินเข้า-ออกลิ้นชัก',
  cashKinds: { PAID_IN: 'เงินเข้า (เติมเงินทอน)', PAID_OUT: 'จ่ายออก (ซื้อของ)', DROP: 'นำเงินออกไปเก็บ' },
  cashMoveAmount: 'จำนวนเงิน (บาท)',
  cashMoveReason: 'เหตุผล / รายการ',
  // Q3b-14 · D54: worded without the expected-cash figure — the drawer stays counted blind (Q3b-3 · D52)
  cashOverDrawerWarning: 'จำนวนนี้มากกว่าเงินสดที่ควรมีในลิ้นชัก ณ ตอนนี้ — ตรวจสอบให้แน่ใจก่อนบันทึก',
  cashOverDrawerConfirm: 'ยืนยันบันทึกทั้งที่เกิน',
  save: 'บันทึก',

  // แผน 4 — สต็อก
  stockMenu: 'สต็อก',
  stockMenuAlerts: (n: number): string => `สต็อก ⚠ ${n}`,
  stockTitle: 'สต็อก',
  stockTotalValue: 'มูลค่าสต็อกรวม',
  stockFilterAll: 'ทั้งหมด',
  stockFilterReorder: 'ต้องสั่งซื้อ',
  stockFilterBases: 'เบส',
  stockOnHand: 'คงเหลือ',
  stockValue: 'มูลค่า',
  stockStatus: { ok: 'ปกติ', low: 'ใกล้หมด', out: 'หมด', negative: 'ติดลบ' },
  stockExpiry: { none: '', fresh: 'หมดอายุ', soon: 'ใกล้หมดอายุ', expired: 'หมดอายุแล้ว' },
  stockExpiresAt: (label: string, at: string): string => `${label} ${at}`,
  stockNoExpiry: 'ไม่มีวันหมดอายุ',
  stockLastCount: (at: string): string => `นับสต็อกล่าสุด ${at}`,
  stockNeverCounted: 'ยังไม่เคยนับสต็อก',
  stockCountDue: 'ถึงเวลานับสต็อกประจำสัปดาห์แล้ว',
  stockNoItems: 'ไม่มีรายการ',
  baseExpiredBanner: (names: string): string => `เบสหมดอายุ: ${names} — ทิ้งแล้วทำใหม่ (หน้าสต็อก)`,
  navProduce: 'ทำเบส',
  navReceive: 'รับของเข้า',
  navCount: 'นับสต็อก',
  navCountResume: 'นับสต็อกต่อ',
  navAdjust: 'ปรับสต็อก',
  discard: 'ทิ้ง',
  discardTitle: (name: string): string => `ทิ้ง${name}ที่เหลือทั้งหมด`,
  discardConfirm: (qty: string): string => `ยืนยันทิ้ง ${qty}`,
  useUnitOption: (unit: string): string => `${unit} (หน่วยใช้)`,
  errQtyFormat: 'จำนวนต้องเป็นตัวเลข ทศนิยมไม่เกิน 3 ตำแหน่ง ไม่เกิน 9999',
  errChooseItem: 'เลือกสินค้าก่อน',
  stockInactive: 'เลิกขาย',
  // fix round 1, review [Important]: mirrors ReceiveScreen's client-side price-jump preview — the same ½×–2× bound
  // the API enforces (MAX_YIELD_FACTOR), shown near the input and checked before saving, not only after a round trip.
  errYieldRange: (range: string): string => `ยอดที่ได้จริงต้องอยู่ระหว่าง ${range}`,

  produceTitle: 'ทำเบส',
  produceChooseBase: 'เลือกเบส',
  produceScale: 'จำนวน batch',
  produceScaleCustom: 'หรือพิมพ์เอง (เช่น 0.75)',
  produceComponents: 'ส่วนประกอบที่ต้องใช้',
  produceYield: (unit: string): string => `ได้จริง (${unit})`,
  produceYieldRange: (range: string): string => `ยอมรับได้ (½×–2× ของสูตร): ${range}`,
  produceLeftover: (qty: string, state: string): string => `ยังมีเบสเดิมเหลือ ${qty}${state === '' ? '' : ` · ${state}`}`,
  produceDiscardFirst: 'ทิ้งของเก่าก่อน',
  produceSave: 'บันทึกทำเบส',
  produceDone: (name: string, cost: string, expires: string): string => `บันทึก${name}แล้ว · ต้นทุน ${cost} · ${expires}`,

  receiveTitle: 'รับของเข้า',
  receiveSupplier: 'ร้าน / ผู้ขาย',
  receiveNote: 'หมายเหตุ',
  receiveItem: 'สินค้า',
  receiveUnit: 'หน่วย',
  receiveQty: 'จำนวน',
  receiveLineTotal: 'ราคารวม (บาท)',
  receiveAdd: 'เพิ่มรายการ',
  receiveSum: 'รวมทั้งใบ',
  receivePaidDrawer: 'จ่ายด้วยเงินในลิ้นชัก (บันทึกจ่ายออกให้อัตโนมัติ)',
  receivePaidDrawerNoShift: 'จ่ายจากลิ้นชักได้เมื่อเปิดกะอยู่เท่านั้น',
  receiveJump: (pct: string): string => `ราคาต่างจากครั้งก่อน ${pct}`,
  receiveConfirmPrice: 'ยืนยันราคานี้',
  receiveSave: 'บันทึกรับของ',
  receiveDone: (total: string): string => `บันทึกรับของแล้ว รวม ${total}`,
  errLineTooLarge: (max: string): string => `ราคารวมต่อรายการต้องไม่เกิน ${max}`,
  errTooManyLines: (max: number): string => `รับของเข้าได้สูงสุด ${max} รายการต่อใบ`,
  errDrawerPayTooLarge: (max: string): string => `จ่ายจากลิ้นชักได้ไม่เกิน ${max} ต่อครั้ง — ลดยอด หรือปิด "จ่ายด้วยเงินในลิ้นชัก" แล้วจ่ายด้วยวิธีอื่น`,
  remove: 'ลบ',

  adjustTitle: 'ปรับสต็อก (เบิกของออก)',
  adjustReasons: { WASTE: 'ของเสีย', EXPIRED: 'หมดอายุ', TRIAL: 'ทดลองสูตร', GIVEAWAY: 'แจก / ชดเชย', OTHER: 'อื่น ๆ' },
  adjustModeItems: 'เป็นวัตถุดิบ',
  adjustModeDrinks: 'เป็นแก้ว (ตามสูตร)',
  adjustProduct: 'เมนู',
  adjustDrinkQty: 'จำนวนแก้ว',
  adjustAdd: 'เพิ่มรายการ',
  adjustReason: 'เหตุผล',
  adjustSave: 'บันทึกเบิกของออก',
  adjustDone: (n: number): string => `บันทึกแล้ว ${n} รายการ`,
  errChooseReason: 'เลือกประเภทก่อน',
  errNothingToAdjust: 'ยังไม่มีรายการ',

  countTitle: 'นับสต็อก',
  // review m-1 (final review): the book figure of a counted item is frozen at the moment its line is saved (T4-2) —
  // a receipt, batch, or "not made" void entered later that same day, but from stock that physically moved before
  // the count, lands on top of the frozen figure and overstates the item until next week's count corrects it.
  countCutoffHint: 'บันทึกรับของ/ทำเบสให้ครบก่อนเริ่มนับ',
  countStart: 'เริ่มนับ',
  countScopeKey: 'ชุดหลัก',
  countScopeAll: 'ทั้งหมด',
  countBlindHint: 'นับของจริงแล้วกรอกเป็นหน่วยเต็ม + เศษ — ระบบแสดงส่วนต่างหลังบันทึกแต่ละรายการ (แก้ตัวเลขได้ ยอดบัญชียังเป็นของตอนนับครั้งแรก)',
  countSaveLine: 'บันทึก',
  // review I-2 (fix round 1): a blank field is refused — never silently saved as 0 — so an accidental tap on
  // "บันทึก" cannot zero out a good count. Typing an explicit 0 is still how an empty shelf is recorded.
  errCountBlank: 'ต้องกรอกจำนวนที่นับ — ถ้าของหมดแล้วให้พิมพ์ 0',
  errCountTooLarge: (max: string): string => `จำนวนที่นับต้องไม่เกิน ${max}`,
  countRecount: 'แก้ตัวเลข', // I-9: the book figure stays as frozen when the item was first counted
  // m-2 (Task 7 review, carried into Task 12): "แก้ตัวเลข" fixes a typo only — it never re-freezes the book figure.
  // A genuine recount after sales must go through "ไม่นับรายการนี้" then a fresh save, which does re-freeze it.
  countRecountHint: 'แก้ตัวเลขที่พิมพ์ผิดเท่านั้น ยอดบัญชียังคงเป็นของตอนนับครั้งแรก — ถ้ามีขายหรือรับของระหว่างที่รอ ให้กด "ไม่นับรายการนี้" แล้วนับใหม่ ระบบจะตั้งยอดบัญชีใหม่ตามปัจจุบัน',
  countUnits: (unit: string, size: string): string => `${unit} เต็ม (${size})`,
  countRest: (useUnit: string): string => `เศษ (${useUnit})`,
  // review I-2 (fix round 1): was "leave it blank (= 0)" — a blank field is now refused, so the hint must say to
  // type the explicit 0 instead.
  countOpeningHint: 'นับครั้งแรก (ยอดยกมา) — ต้องนับให้ครบทุกรายการ ของที่ไม่มีให้พิมพ์ 0 แล้วกด "บันทึก"',
  countSkip: 'ไม่นับรายการนี้', // m-2: the genuine-recount path — removes the draft line so the next save re-freezes the book figure
  countOpening: 'ยอดยกมาครั้งแรก',
  countCounted: (qty: string): string => `นับได้ ${qty}`,
  countVariance: (qty: string, baht: string): string => `ส่วนต่าง ${qty} (${baht})`,
  countLines: (n: number): string => `นับแล้ว ${n} รายการ`,
  countTotalVariance: 'ส่วนต่างรวม',
  countClose: 'ปิดใบนับ',
  countCloseConfirm: 'ยืนยันปิดใบนับ (ปรับยอดตามที่นับ)',
  countClosed: (n: number, baht: string): string => `ปิดใบนับแล้ว ปรับ ${n} รายการ · ส่วนต่างรวม ${baht}`,

  // Task 19 — ใบเสร็จ · ประวัติบิล · รายละเอียดบิล · บิลบอท/เว็บวันนี้ · ยอดไม่ตรงระบบกลาง (spec §4.3, §4.6, §4.7, §4.8, §6.4 · D61)
  doneSoldBy: (name: string): string => `ขายโดย ${name} · แท็บเล็ต`,
  navCentralOrders: 'บิลบอท/เว็บวันนี้',

  // §6.4: dayo's state of this bill (CentralStateChip)
  centralPending: 'ยังไม่ถึงระบบกลาง',
  centralSent: (orderNo: string): string => `ระบบกลาง ${orderNo}`,
  centralProblem: (reason: string): string => `ส่งไม่ผ่าน: ${reason}`,
  centralExcluded: 'นอกระบบกลาง',
  centralLegacy: 'บิลก่อนเชื่อมระบบกลาง',
  // review item 23: a voided bill whose order row WAS sent — dayo still counts it as a sale.
  centralVoidLocalOnly: 'ยกเลิกในเครื่องเท่านั้น — ระบบกลางยังนับเป็นยอดขาย',

  // §4.3: dayo's computed total vs. what was charged, shown down to 1 satang · §4.8 duplicate-of-bot label
  orderDiff: (computed: string, diff: string): string => `ระบบกลางคิด ${computed} (ต่าง ${diff})`,
  orderDup: (orderNos: string): string => `อาจซ้ำกับบิลบอท ${orderNos}`,

  // §4.6 · O1 pending: dayo_edit shown read-only — no button anywhere edits a bill from the tablet (ADR-0050)
  dayoEditKindEdit: 'เจ้าของแก้บิลนี้บนเว็บ',
  dayoEditKindCancel: 'เจ้าของยกเลิกบิลนี้บนเว็บ',
  dayoEditKindOther: 'ระบบกลางเปลี่ยนบิลนี้',
  dayoEditReason: (reason: string): string => `เหตุผล: ${reason}`,
  dayoEditMoneyNote: 'ยอดในเครื่องคือเงินที่เก็บจริง',
  orderDayoEditChipEdit: 'แก้บนเว็บ',
  orderDayoEditChipCancel: 'ยกเลิกบนเว็บ',

  // §4.6: today's bot/web bills, online only
  centralOrdersTitle: 'บิลบอท/เว็บวันนี้',
  centralOrdersOffline: 'ต้องออนไลน์เพื่อดูบิลจากบอท/เว็บ',
  centralOrdersRefresh: 'รีเฟรช',
  centralOrdersDuplicate: 'อาจซ้ำ',
  centralOrdersEmpty: 'ยังไม่มีบิลจากบอท/เว็บวันนี้',
  centralOrdersUnknownBy: 'ไม่ทราบผู้บันทึก',

  // §4.3, review item 23: owner's "ยอดไม่ตรงระบบกลาง" (R11)
  priceDiffTitle: 'ยอดไม่ตรงระบบกลาง',
  priceDiffAmountMismatch: 'ต่างเกิน ฿1',
  priceDiffVoidLocalOnly: 'ยกเลิกในเครื่องเท่านั้น — ระบบกลางยังนับเป็นยอดขาย (ก้อน 3 จะจัดการเงิน)',
  priceDiffEmpty: 'ไม่มียอดไม่ตรงระบบกลาง',
  priceDiffCatalog: (version: string): string => `ฉบับแคตตาล็อก ${version}`,
  priceDiffPos: (amount: string): string => `POS ${amount}`,
  priceDiffCentral: (amount: string): string => `ระบบกลาง ${amount}`,
  priceDiffDiff: (amount: string): string => `ต่าง ${amount}`,

  // VOID_NOT_ALLOWED with a structured detail prefix (ruling R11 · same-day-only) — the code already writes this
  // exact Thai text after the prefix (void.ts); matched by the prefix (never by parsing the rest as free text).
  errVoidSameDayOnly: 'ยกเลิกได้เฉพาะวันเดียวกับวันขาย',
  errVoidOwnBillsOnly: 'staff และ manager ยกเลิกได้เฉพาะบิลที่ตัวเองขาย',

  // Task 20 — แถบเตือน · หน้าสถานะระบบ · หน้า "ส่งไม่ผ่าน" (spec §4.4 ข้อ 9, §6.3, §6.4, §6.7, §10.5 · D80 · ruling R8)
  bannerKeyRevoked: 'กุญแจเครื่องถูกยกเลิก — ให้เจ้าของตั้งค่าใหม่',
  bannerKeyForbidden: 'กุญแจเครื่องไม่มีสิทธิ์ส่งข้อมูล',
  bannerApiOff: 'ระบบกลางปิด API อยู่ — บิลเก็บในเครื่อง จะส่งเมื่อเปิด',
  bannerClock: (n: number): string => `นาฬิกาเครื่องต่างจากระบบกลาง ${n} นาที — ตั้งเวลาเครื่องให้ตรง (ขายต่อได้)`,
  bannerPricing: 'ตัวคิดราคาในเครื่องไม่ตรงกับระบบกลาง — ขายได้ แจ้งทีม POS',
  bannerCatalog: 'แคตตาล็อกจากระบบกลางอ่านไม่ได้ — ใช้ฉบับเดิมอยู่',
  bannerStaleQueue: 'มีบิลค้างส่งเกิน 24 ชม.',
  bannerClockFarAhead: (n: number): string => `เวลาในบิล ${n} รายการล้ำระบบกลางเกิน 24 ชม. — ตั้งนาฬิกาแท็บเล็ตให้ตรง แล้วกด "ส่งตอนนี้"`,
  bannerProblems: (n: number): string => `ส่งไม่ผ่าน ${n} บิล`,
  bannerGoStatus: 'ไปหน้าสถานะระบบ',

  // /status (ทุกบทบาทดูได้ · ปุ่มตั้งค่าเฉพาะ owner)
  statusTitle: 'สถานะระบบ',
  statusKeyLabel: 'กุญแจเครื่อง',
  statusBaseUrlLabel: 'ที่อยู่ระบบกลาง',
  statusNotLinked: 'ยังไม่เชื่อมกับระบบกลาง',
  statusApiStateLabel: 'สถานะ API',
  statusApiStates: { ok: 'ปกติ', unauthorized: 'ถูกยกเลิก', forbidden: 'ไม่มีสิทธิ์ส่งข้อมูล', disabled: 'ปิดอยู่', bad_base_url: 'ที่อยู่ไม่ถูกต้อง' },
  statusApiStateUnknown: 'ไม่ทราบ',
  statusClockNever: 'ยังไม่วัด',
  statusClockOk: (n: number): string => `ตรงกับระบบกลาง (ต่าง ${n} นาที)`,
  statusClockWarn: (n: number): string => `ต่างจากระบบกลาง ${n} นาที`,
  statusCatalogLine: (version: string, at: string): string => `ฉบับ ${version} · เช็กล่าสุด ${at}`,
  statusCatalogNever: 'ยังไม่เคยเช็กแคตตาล็อก',
  statusPricingOk: 'ตัวคิดราคาตรงกับระบบกลาง',
  statusPricingMismatch: 'ตัวคิดราคาไม่ตรงกับระบบกลาง — แจ้งทีม POS',
  statusPricingCommitUnknown: 'ไม่ทราบ (ระบบกลางไม่ได้ระบุรุ่น)',
  statusPricingCommitLabel: (commit: string): string => `รุ่นตัวคิดราคา ${commit}`,
  statusLastPush: (at: string): string => `ส่งล่าสุด ${at}`,
  statusLastPushNever: 'ยังไม่เคยส่ง',
  statusPendingLine: (n: number): string => `ค้างส่ง ${n} รายการ`,
  statusProblemsLine: (n: number): string => `ส่งไม่ผ่าน ${n} รายการ`,
  statusPriceDiffLine: (n: number): string => `ยอดไม่ตรงระบบกลาง ${n} บิล`,
  statusSyncNow: 'ส่งตอนนี้',
  statusReplaceKeyTitle: 'ตั้งกุญแจใหม่',
  statusReplaceKeyApprover: 'เจ้าของผู้อนุมัติ',
  statusReplaceKeyPin: 'PIN เจ้าของผู้อนุมัติ',
  statusReplaceKeySave: 'บันทึกกุญแจใหม่',
  statusReplaceKeyDone: 'เปลี่ยนกุญแจแล้ว',

  // /sync-problems (owner เท่านั้น — spec §6.4)
  syncProblemsTitle: 'ส่งไม่ผ่าน',
  syncProblemsEmpty: 'ไม่มีรายการส่งไม่ผ่าน',
  // ก้อน 3 (Task 16 · carried item 1): ทุก 7 ชนิดที่ขึ้นหน้านี้ได้ (PushKind) — 2 ชนิดบิลเดิม + 5 ชนิดกะ/เงิน
  syncProblemKind: {
    order: 'บิล',
    order_void: 'ยกเลิกบิล',
    order_off_catalog: 'บิลนอกแคตตาล็อก',
    shift_open: 'เปิดกะ',
    cash_movement: 'เงินเข้า-ออก',
    cash_count: 'นับเงิน',
    shift_close: 'ปิดกะ (Z)',
  },
  syncProblemDetail: (detail: string): string => `เหตุผล: ${detail}`,
  syncProblemClockAheadTag: 'รอเวลา — ยังส่งอยู่ทุก 1 นาที',
  syncProblemClockAheadHint: 'ตั้งนาฬิกาแท็บเล็ตให้ตรง แล้วกด "ส่งตอนนี้"',
  remedyRetry: 'ลองใหม่',
  remedyRenumber: 'ออกเลขใบเสร็จใหม่',
  remedyRemapCode: 'เลือกรหัสแทน',
  remedyRemapStaff: 'เลือกผู้ขายแทน',
  remedyExclude: 'ปิดเป็นรายการนอกระบบกลาง',
  remedyExport: 'ส่งออก JSON',
  syncExcludeWarning: 'บิลนี้ยังอยู่ในรายงานเครื่อง แต่จะไม่ถึงระบบกลาง',
  syncExcludeClockAheadWarning: 'บิลนี้จะไม่ถึงระบบกลาง — ยอดขายจริงจะหายจากฐานกลางจนก้อน 3',
  syncExcludeConfirm: 'ยืนยันปิดเป็นรายการนอกระบบกลาง',
  approvalPinLabel: 'PIN เจ้าของ',
  approvalReasonLabel: 'เหตุผล',
  approvalOk: 'ยืนยัน',
  remapCodeFieldLine: 'บรรทัดสินค้า',
  remapCodeFieldChannel: 'ช่องทางขาย',
  remapCodeFieldPayment: 'วิธีชำระ',
  remapCodeLineIndex: 'บรรทัดที่ (เริ่มที่ 0)',
  remapCodeMenu: 'เมนูแทน',
  remapCodeSize: 'ขนาดแทน',
  remapCodeSweetness: 'ความหวานแทน',
  remapCodeGradeOnly: 'ระบบกลางไม่รู้จักเกรดของบรรทัดนี้ — เมนู ขนาด และความหวานคงเดิม เปลี่ยนเป็นเกรดเริ่มต้นเท่านั้น',
  remapCodeLineOption: (index: number, code: string, size: string, sweetness: string): string => `บรรทัดที่ ${index} · ${code} ${size} ${sweetness}`,
  remapStaffLabel: 'พนักงานแทน',

  // ก้อน 3 (Task 16 · spec §6.2, §6.4, §6.6 · D97 · ruling R9, R11, R12, R14)
  remedyCloseOffCatalog: 'ปิดเป็นบิลนอกแคตตาล็อก',
  remedyAcknowledge: 'รับทราบ — บิลอยู่ในระบบกลางแล้ว',
  remedyReconfirm: 'เจ้าของยืนยันด้วย PIN ใหม่',
  remedyExcludeLocal: 'ปิดไว้ในเครื่อง',
  offCatalogWarning: 'บิลนี้จะเข้าระบบกลางเป็น "บิลนอกแคตตาล็อก": ยอดเงินเท่าเดิม ต้นทุนไม่ทราบ ไม่ตัดสต็อก — ห้ามบันทึกเงินเข้า/ออกเพื่อชดเชย',
  offCatalogBadge: 'นอกแคตตาล็อก',
  offCatalogRuleHint: 'ระบบกลางไม่รับบิลนอกแคตตาล็อกใบนี้ (ไม่มีประวัติถูกปฏิเสธ / ก่อนวันเริ่มใช้กะ / เกินเพดานยอด) — ถ้าเกินเพดาน เจ้าของเพิ่มเพดานบนเว็บ dayo แล้วกด "ลองใหม่"',
  centralMismatchBanner: 'บิลในระบบกลางไม่ตรงกับเครื่อง',
  centralMismatchLine: (orderNo: string, central: string, local: string): string => `${orderNo}: ระบบกลาง ${central} · เครื่อง ${local}`,
  shiftConflictBanner: 'ข้อมูลกะชนกับระบบกลาง — แนะนำให้เจ้าของเปลี่ยนกุญแจเครื่อง',
  scopeBanner: (scope: string): string => `กุญแจเครื่องไม่มีสิทธิ์ ${scope} — เพิ่มสิทธิ์บนเว็บ dayo`,
  voidRejectedHint: (orderNo: string): string => `ให้เจ้าของยกเลิกบิล ${orderNo} บนเว็บ dayo (พร้อมเหตุผล) แล้วกด "ปิดไว้ในเครื่อง"`,
  keyReplacedHint: 'กะนี้เริ่มก่อนเปลี่ยนกุญแจเครื่องครั้งล่าสุด — ปิดทีละแถว หรือ "เก็บกะนี้ไว้ในเครื่อง" ทั้งกะ',
  problemCentralMismatch: 'ยอด/วิธีชำระในระบบกลางไม่ตรงกับเครื่อง',
  // ก้อน 3: ข้อความของการ์ด "รอ" (waiting) ตาม `SyncProblemDto.waiting`
  problemWaitingHint: {
    clock: 'เวลาบิลล้ำเวลาระบบกลางเกิน 24 ชม. — ตั้งนาฬิกาแท็บเล็ตให้ตรง แล้วกด "ส่งตอนนี้"',
    scope: 'รอสิทธิ์จากระบบกลาง — เพิ่มสิทธิ์บนเว็บ dayo หรือ "ปิดไว้ในเครื่อง" ได้หลัง 7 วัน',
    unsupported: 'ระบบกลางเลิกรองรับรายการนี้แล้ว — ปิดไว้ในเครื่องเพื่อปลดกะที่ค้างอยู่ข้างหลัง',
  },
  blocksLaneRows: (n: number): string => `กะที่รออยู่ข้างหลังแถวนี้ ${n} รายการ`,
  shiftLaneHeldBanner: (n: number): string => `ช่องกะติดคิว ${n} รายการ — ไปหน้า "ส่งไม่ผ่าน"`,
  setupLastZ: (n: number | null): string => (n === null ? 'Z ล่าสุดในระบบกลาง: ยังไม่มี' : `Z ล่าสุดในระบบกลาง: ${n}`),
  setupConfirmLastZ: 'ตรวจแล้ว — ใบปิดกะใบถัดไปของเครื่องนี้จะต่อจากเลขนี้',
  countNotInDayo: (n: number, voidRefund: string): string => `${n} บิลในใบปิดกะนี้จะไม่ถึงระบบกลาง — คืนเงินบิลยกเลิกในนั้น ${voidRefund} ยังส่งเข้าระบบกลาง`,
  keepShiftLocalButton: 'เก็บกะนี้ไว้ในเครื่อง',
  keepShiftLocalWarning: 'ใบปิดกะของกะนี้จะออกในเครื่องเท่านั้น — กะฝั่งระบบกลางยังเปิดอยู่ บิลบอทในช่วงนี้จะไม่อยู่ใน Z ใด และระบบกลางจะเห็นเลข Z ขาดไปหนึ่งใบ',
  skipCountFloorButton: 'ข้ามการตรวจเวลาที่ล้ำ',
  skipCountFloorWarning: 'บิลบอทของช่วงเวลานี้อาจถูกนับซ้ำหรือไม่ถูกนับเลย',
  skipCountFloorDone: (n: number): string => `ข้ามแล้ว ${n} รายการ`,

  // fu app-version — เวอร์ชันที่กำลังใช้งาน (/status เต็มบรรทัด, BrandBar ย่อ)
  statusVersionLine: (version: string, commit: string, builtAt: string): string => `เวอร์ชัน v${version} · commit ${commit} · build ${builtAt}`,
} as const
