// ข้อความบนจอทั้งหมดของแอปขาย — แก้คำได้ที่ไฟล์นี้ไฟล์เดียว (e2e อ้าง data-testid ไม่อ้างข้อความ)
export const TH = {
  appName: 'DA-YO POS',
  loading: 'กำลังโหลด…',
  retry: 'ลองใหม่',
  back: 'กลับ',
  cancel: 'ยกเลิก',
  lock: 'ล็อก',
  dbError: 'เปิดฐานข้อมูลในเครื่องไม่ได้',
  dbErrorTwoTabs: 'ถ้าเปิดแอปนี้อยู่ในแท็บหรือหน้าต่างอื่น ให้ปิดอันนั้นก่อนแล้วกดลองใหม่',
  pendingSync: (n: number): string => `ยังไม่ส่งขึ้นเซิร์ฟเวอร์ ${n} รายการ`,
  storageNotPersistent: 'ข้อมูลในเครื่องยังไม่ถูกล็อกไว้ (อาจถูกล้าง) — ติดตั้งแอปลงหน้าจอหลัก',
  errUnexpected: 'เกิดข้อผิดพลาด ลองใหม่อีกครั้ง',

  setupTitle: 'ตั้งค่าเครื่องครั้งแรก',
  setupDeviceName: 'ชื่อเครื่อง',
  setupDeviceNameDefault: 'แท็บเล็ตหน้าร้าน',
  setupReceiptPrefix: 'อักษรนำหน้าเลขที่บิล (A–Z)',
  setupOwner: (n: number): string => `เจ้าของคนที่ ${n}`,
  setupDisplayName: 'ชื่อที่แสดง',
  setupPin: 'PIN ตัวเลข 4–6 หลัก',
  setupPinConfirm: 'ยืนยัน PIN อีกครั้ง',
  setupPromptPayId: 'หมายเลขพร้อมเพย์ (เบอร์มือถือ 10 หลัก / เลขบัตร 13 หลัก / e-Wallet 15 หลัก)',
  setupSave: 'บันทึกและเริ่มใช้งาน',

  loginTitle: 'ใครกำลังใช้งาน',
  loginEnterPin: (name: string): string => `ใส่ PIN ของ ${name}`,

  shiftOpenTitle: 'เปิดกะ',
  shiftOpeningFloat: 'เงินทอนในลิ้นชักตอนเปิดกะ (บาท)',
  shiftOpen: 'เปิดกะ',

  tabBestSellers: 'ขายดี',
  cart: 'ตะกร้า',
  cartEmpty: 'ยังไม่มีรายการ',
  subtotal: 'รวม',
  discount: 'ส่วนลด',
  total: 'ยอดสุทธิ',
  payCash: 'เงินสด',
  payQr: 'QR พร้อมเพย์',
  size: 'ขนาด',
  sweetness: 'ความหวาน',
  sweetShort: 'หวาน',
  addToCart: 'เพิ่มลงตะกร้า',
  clearCart: 'ล้างตะกร้า',
  noPrice: 'ไม่มีราคา',
  orders: 'บิลวันนี้',

  discountTitle: 'ส่วนลดท้ายบิล',
  discountAmount: 'จำนวนเงิน (บาท)',
  discountReason: 'เหตุผล',
  discountApply: 'ใช้ส่วนลด',
  discountRemove: 'ลบส่วนลด',

  cashTitle: 'รับเงินสด',
  exact: 'พอดี',
  tendered: 'รับเงินมา (บาท)',
  change: 'เงินทอน',
  confirmCash: 'ยืนยันรับเงิน',

  qrTitle: 'สแกนจ่ายด้วยพร้อมเพย์',
  qrReceived: 'ได้รับเงินแล้ว',

  priceChanged: (from: string, to: string): string => `ราคาเปลี่ยน: ยอดเดิม ${from} → ยอดใหม่ ${to} — ตรวจยอดแล้วกดยืนยันอีกครั้ง`,
  qrRescan: 'ให้ลูกค้าสแกน QR ใหม่ที่ยอดใหม่',

  queue: 'คิว',
  receiptNo: 'เลขที่บิล',
  newSale: 'ขายต่อ',

  statusPaid: 'ชำระแล้ว',
  statusVoided: 'ยกเลิกแล้ว',
  methodCash: 'เงินสด',
  methodPromptPay: 'พร้อมเพย์',
  noOrders: 'ยังไม่มีบิลในกะนี้',
  lines: 'รายการ',
  payment: 'การชำระ',
  events: 'ประวัติเหตุการณ์',
  voidOrder: 'ยกเลิกบิล',

  voidTitle: (receiptNo: string): string => `ยกเลิกบิล ${receiptNo}`,
  voidReason: 'เหตุผล',
  voidReasonPresets: ['ลูกค้าเปลี่ยนใจ', 'กดผิดเมนู', 'ทำผิดสูตร'], // 3 preset buttons + free text (D48 Q3-14)
  voidMadeQuestion: 'ทำเครื่องดื่มไปแล้วหรือยัง',
  voidMadeYes: 'ทำแล้ว (ทิ้งเป็นของเสีย)',
  voidMadeNo: 'ยังไม่ทำ (คืนวัตถุดิบเข้าสต็อก)',
  voidCashRefund: (amount: string): string => `คืนเงินสด ${amount} จากลิ้นชัก`,
  voidQrRefundRef: 'เลขอ้างอิงการโอนคืน',
  voidApprover: 'เจ้าของที่อนุมัติ',
  voidConfirm: 'ยืนยันยกเลิกบิล',

  errDbOpenFailed: 'เปิดฐานข้อมูลในเครื่องไม่ได้',
  errNeedsSetup: 'เครื่องนี้ยังไม่ได้ตั้งค่า',
  errAlreadySetUp: 'เครื่องนี้ตั้งค่าไปแล้ว',
  errBadInput: 'ข้อมูลไม่ถูกต้อง',
  errPinFormat: 'PIN ต้องเป็นตัวเลข 4–6 หลัก',
  errPinMismatch: 'PIN สองช่องไม่ตรงกัน',
  errPinWrong: 'PIN ไม่ถูกต้อง',
  errPinLocked: 'ใส่ PIN ผิดหลายครั้ง — รอสักครู่แล้วลองใหม่',
  errPinLockedFor: (seconds: number): string => `ใส่ PIN ผิดหลายครั้ง — ลองใหม่ใน ${seconds} วินาที`,
  errNotOwner: 'ต้องเป็นเจ้าของร้านเท่านั้น',
  errNoOpenShift: 'ยังไม่ได้เปิดกะ',
  errShiftAlreadyOpen: 'มีกะเปิดอยู่แล้ว',
  errEmptyCart: 'ตะกร้าว่าง',
  errNoPrice: 'เมนูนี้ยังไม่มีราคา ขายไม่ได้',
  errNoRecipe: 'เมนูนี้ยังไม่มีสูตร ขายไม่ได้',
  errTenderTooLow: 'รับเงินน้อยกว่ายอด',
  errDiscountTooBig: 'ส่วนลดต้องน้อยกว่ายอดรวม',
  errPriceChanged: 'ราคาเปลี่ยนแล้ว — กำลังปรับราคาในตะกร้า',
  errReasonRequired: 'ต้องใส่เหตุผล',
  errNoPromptPayId: 'ยังไม่ได้ตั้งหมายเลขพร้อมเพย์',
  errOrderNotFound: 'ไม่พบบิล',
  errVoidNotAllowed: 'ยกเลิกได้เฉพาะบิลที่ชำระแล้วในกะที่เปิดอยู่',
  errChooseMade: 'เลือกก่อนว่าทำเครื่องดื่มไปแล้วหรือยัง',
  errRefundRefRequired: 'ต้องใส่เลขอ้างอิงการโอนคืน',
  errShiftChanged: 'ยอดในกะเปลี่ยนระหว่างนับเงิน — ดูยอดใหม่แล้วยืนยันอีกครั้ง',
  errVarianceReasonRequired: 'เงินขาด/เกินเกินเกณฑ์ ต้องใส่เหตุผล',
  errZNotFound: 'ไม่พบรายงาน Z',
  errBackupFailed: 'สำรองไฟล์ไม่สำเร็จ ลองใหม่อีกครั้ง',
  errZChainBroken: 'รายงาน Z ใบก่อนหน้าถูกแก้ไขหรือไฟล์เสีย (ลายเซ็นไม่ตรง) — เจ้าของกรอก PIN อีกครั้งเพื่อรับทราบ แล้วปิดกะต่อได้ (Z ใบนี้จะมีป้ายเตือนถาวร)',
  errCountFormat: 'จำนวนต้องเป็นตัวเลขจำนวนเต็ม 0–99999',
  errCountFirst: 'กด "นับเสร็จ" ก่อน',

  // แผน 3b — กะ / X / Z / เงินเข้า-ออก / สำรองไฟล์
  shiftMenu: 'กะ / รายงาน X',
  xTitle: 'รายงาน X (ยอดสด ณ ตอนนี้)',
  xExpectedHidden: 'เงินสดที่ควรมีแสดงหลังนับเงินตอนปิดกะเท่านั้น (นับแบบไม่เห็นยอด)',
  shiftInfo: (date: string, name: string): string => `วันทำการ ${date} · เปิดกะโดย ${name}`,
  quickOpenBadge: 'เปิดกะด่วน',
  salesTitle: 'ยอดขาย',
  receiptCount: 'จำนวนบิล',
  voidCount: 'บิลยกเลิก',
  grossSales: 'ยอดขายรวม (รวมบิลยกเลิก)',
  discounts: 'ส่วนลดรวม',
  voidedSales: 'ยอดบิลยกเลิก',
  netSales: 'ยอดขายสุทธิ',
  cashSales: 'รับเงินสด',
  qrSummaryTitle: 'พร้อมเพย์ (เทียบกับแอปธนาคาร)',
  qrSales: 'รับพร้อมเพย์',
  qrRefunded: 'โอนคืน (บิลยกเลิก)',
  qrNet: 'พร้อมเพย์สุทธิ',
  bankQrTotal: 'ยอดพร้อมเพย์ในแอปธนาคาร (บาท · ไม่บังคับ)',
  bankQrNotEntered: 'ไม่ได้กรอก',
  qrDifference: 'ส่วนต่าง (แอปธนาคาร − พร้อมเพย์สุทธิ)',
  drawerTitle: 'เงินสดในลิ้นชัก',
  openingFloat: 'เงินทอนตั้งต้น',
  voidRefunds: 'คืนเงินบิลยกเลิก',
  paidIn: 'เงินเข้า',
  paidOut: 'จ่ายออก',
  drops: 'นำเงินออกไปเก็บ',
  expectedCash: 'เงินสดที่ควรมี',
  cashMovesTitle: 'เงินเข้า-ออกที่บันทึก',
  voidListTitle: 'บิลที่ยกเลิก',
  noVoids: 'ไม่มีบิลยกเลิก',
  voidWasMade: 'ทำแล้ว (ของเสีย)',
  voidNotMade: 'ยังไม่ทำ (คืนสต็อก)',
  voidApprovedBy: (name: string): string => `อนุมัติโดย ${name}`,
  negativeBasesTitle: 'เบสติดลบ (ลืมบันทึกทำเบส?)',
  noNegativeBases: 'ไม่มีเบสติดลบ',
  pendingAtClose: (n: number): string => `ยังไม่ส่งขึ้นเซิร์ฟเวอร์ ${n} รายการ — ข้อมูลอยู่ในเครื่องและในไฟล์สำรอง`,
  closeShift: 'ปิดกะ',
  closeTitle: 'ปิดกะ — นับเงินในลิ้นชัก',
  denomination: 'ชนิด',
  pieces: 'จำนวน',
  countedTotal: 'นับได้',
  countDone: 'นับเสร็จ ดูส่วนต่าง',
  countEdit: 'แก้จำนวนที่นับ',
  variance: 'ส่วนต่าง (นับได้ − ควรมี)',
  varianceReason: 'เหตุผลเงินขาด/เกิน',
  varianceReasonHint: (limit: string): string => `ขาดหรือเกินมากกว่า ${limit} ต้องใส่เหตุผล`,
  closeApprover: 'เจ้าของที่ยืนยันปิดกะ',
  cartNotEmpty: 'ยังมีรายการค้างในตะกร้า — ขายหรือล้างตะกร้าก่อนปิดกะ',
  zChainAck: 'Z ใบก่อนหน้าลายเซ็นไม่ตรง — เจ้าของกรอก PIN อีกครั้งเพื่อรับทราบ ระบบจะคิดยอดสะสมใหม่จาก Z ทุกใบ และติดป้ายเตือนถาวรใน Z ใบนี้',
  zTitle: 'รายงาน Z',
  zList: 'Z ย้อนหลัง',
  noZ: 'ยังไม่มีรายงาน Z',
  zClosedAt: (at: string): string => `ปิดกะเมื่อ ${at}`,
  zGrandTotal: 'ยอดขายสุทธิสะสม (grand total)',
  zHashOk: 'ตรวจลายเซ็นแล้ว ข้อมูลไม่ถูกแก้',
  zHashBad: 'ลายเซ็นไม่ตรง — ข้อมูลอาจถูกแก้',
  zUnreadable: 'ข้อมูล Z นี้อ่านไม่ได้/ถูกแก้ไข',
  zChainWarning: 'Z ใบนี้ปิดหลังพบว่า Z ใบก่อนหน้าลายเซ็นไม่ตรง — ยอดสะสมคิดใหม่จาก Z ทุกใบ (เจ้าของรับทราบด้วย PIN แล้ว)',
  zChainWarningShort: 'Z ก่อนหน้าลายเซ็นไม่ตรง',
  zDone: 'เสร็จ',
  backupTitle: 'สำรองไฟล์ฐานข้อมูล',
  backupHint: 'ไฟล์จะลงในโฟลเดอร์ดาวน์โหลดของแท็บเล็ต — ย้ายไปเก็บที่ Google Drive หรือคอมพิวเตอร์ทุกวัน',
  backupNow: 'ดาวน์โหลดไฟล์สำรอง',
  backupNever: 'ยังไม่เคยสำรอง',
  backupLast: (at: string): string => `สำรองล่าสุด ${at}`,
  backupCheckFile: (name: string): string => `ตรวจว่าเห็นไฟล์ ${name} ในโฟลเดอร์ดาวน์โหลดแล้ว จึงกด "บันทึกไฟล์แล้ว"`,
  backupConfirm: 'บันทึกไฟล์แล้ว',
  backupDone: (name: string): string => `ยืนยันไฟล์สำรอง ${name} แล้ว`,
  backupOwnerOnly: 'สำรองไฟล์ได้เฉพาะเจ้าของร้าน (ในไฟล์มี PIN เก็บแบบแฮช (ไม่ใช่รหัสจริง) และหมายเลขพร้อมเพย์ของร้าน)',
  backupDue: 'ปิดกะแล้วแต่ยังไม่ได้ยืนยันไฟล์สำรอง — สำรองแล้วกด "บันทึกไฟล์แล้ว" ก่อนปิดเครื่อง',
  shiftStale: (date: string): string => `กะของวันที่ ${date} ยังไม่ปิด — ปิดกะก่อนเริ่มวันใหม่`,
  quickOpen: 'เปิดกะด่วน (เงินทอน 0 · เจ้าของเท่านั้น)',
  cashMove: 'เงินเข้า-ออก',
  cashMoveTitle: 'บันทึกเงินเข้า-ออกลิ้นชัก',
  cashKinds: { PAID_IN: 'เงินเข้า (เติมเงินทอน)', PAID_OUT: 'จ่ายออก (ซื้อของ)', DROP: 'นำเงินออกไปเก็บ' },
  cashMoveAmount: 'จำนวนเงิน (บาท)',
  cashMoveReason: 'เหตุผล / รายการ',
  save: 'บันทึก',
} as const
